### ISSUE TITLE
how to fix Database backup error 1

### ISSUE THREAD

**Issue by esgindy** [odoo/docker#102]
when i try to get db Backup of my odoo 9 i got this message
Database backup error: Postgres subprocess ('/usr/bin/pg_dump', '--no-owner', '--file=/tmp/tmpHQQep8/dump.sql', u'rams') error 1

how can i fix this error

**Comment by chermed** [comment]
Odoo is not compatible with postgresql version >= 9.5

**Comment by esgindy** [comment]
so now what can i do i already launched my Odoo at postgresql 9.4 but i change vps server and the new one used postgresql 9.5 so what can i do to got backup and downgrade it to postgresql 9.4

**Comment by sle-odoo** [comment]
Hi,
Odoo should be compatible with any postgres >= 9.3.  A quick google search shows [this](https://www.postgresql.org/message-id/AANLkTins%3DMZXWvpFeshO0-i%3D-HpAeHsvHj9z6xguVL9o@mail.gmail.com) about the pg_dump error 1.

I'm closing this as it is not related to Odoo Docker.

Regards

**Comment by nehemiascr** [comment]
I am experiencing this issue if I use docker with postgres 10+, it works fine if installed in a linux machine

**Comment by sylnsr** [comment]
"Odoo is not compatible with postgresql version >= 9.5" -- this is simply not true

**Comment by chermed** [comment]
@sylnsr  At the time of the issue, the version 9.5.X is not compatible, but now if you upgrate to last 9.5.Y I think that it will works.

The best practice (for the production) is to follow the official documentation https://github.com/docker-library/docs/tree/master/odoo they use 9.4

**Comment by sylnsr** [comment]
@chermed once again your information is not exactly correct. @esgindy opened this Issue on Jan 25, 2017 yet it was announced by @odony on Jan 8, 2016 that 9.5 is **officially** supported.

If you are unable to provide support then perhaps you should let someone more helpful do it instead.

**Comment by chermed** [comment]
@sylnsr I'm sorry if the information is not correct, but I mentioned that you forget to specifiy the X in the version !

**Comment by sylnsr** [comment]
Sorry. I have no clue what you are talking about and I am not about to open any issues to try figure out your complaint.
