### ISSUE TITLE
how to downgrade postgresql 9.5 to 9.3

### ISSUE THREAD

**Issue by esgindy** [odoo/docker#103]
how to downgrade postgresql 9.5 to 9.3
i used odoo at VPS server when i change my VPS the new one used postgresql 9.5 so i faced error when i got backup so how can i downgrade my postgreosql 9.5 to 9.3 without loss any data

**Comment by sle-odoo** [comment]
Hi,
You should just use `pg_dump` and `pg_restore`. Using the import/export from the Odoo UI should also work correctly.

Regards
