### ISSUE TITLE
Longpolling Port should be 8072

### ISSUE THREAD

**Issue by jaredkipe** [odoo/docker#107]
Longpolling port is 8072 by default (including in all of the configuration files in this repo), yet the image exposes 8071 instead.

**Comment by azawawi** [comment]
Also `workers` should be set to 2 for long polling for Discuss app to actually work out of the box.

**Comment by jaredkipe** [comment]
Well, you can expose the port even if you don't use it.  Without workers, long polling will happen through 8069

**Comment by steenzout** [comment]
@jaredkipe nothing prevents from using Odoo's base image, create your own `Dockerfile` and expose port 8072, correct?

**Comment by jaredkipe** [comment]
Oh I have.... https://hub.docker.com/r/hibou/odoo/ and made the change a while ago.  I just though that for consistency sake, they might want to use the same port that Odoo uses by default.

I feel like the whole point of Docker is to get a dependency graph in your mind easily.  So if I have an odoo container running and see that it is exposing 8071, the I'm going to wire Nginx up to that port.  But then if I go to the default config file, its a different port, but I don't realize that right away so I just turn it on.  Now I have a problem and its harder to see why than it should be.

**Comment by anassahmed** [comment]
Is 8071 for `longpolling` in docker? I thought it's for `xmlrpcs` (https) connections.

**Comment by dvusboy** [comment]
So, looking at the code `odoo|openerp/tools/config.py`, `--xmlrpcs-port`, which has a default value of 8071, was removed since 9.0. `--longpolling-port` was added in that release and defaults to 8072. So, I'd think both `Dockerfile` and `odoo.conf` should be updated for tag `9.0` and `10.0`

**Comment by sylnsr** [comment]
As per the included `odoo.conf` file .. 8071 is for [xmlrpcs](https://github.com/odoo/docker/blob/master/12.0/odoo.conf#L37) and 8072 is for [longpolling](https://github.com/odoo/docker/blob/master/12.0/odoo.conf#L22).  Features in the UI that require notifications will not work properly without the longpolling port (e.g. Chat) ... however not everyone uses xml-rpcs .... so I would argue that port 8072 is more important for typical use than 8071.

More over `EXPOSE` is [used for informational purposes](https://medium.freecodecamp.org/expose-vs-publish-docker-port-commands-explained-simply-434593dbc9a3) and does not actually publish the port. To that end, if `odoo.conf` gives that information, why wouldn't the Docker file match that information?
