### ISSUE TITLE
Python dependencies not up to date.

### ISSUE THREAD

**Issue by Fenkiou** [odoo/docker#108]
From [this file](https://github.com/odoo/odoo/blob/10.0/requirements.txt) we can see that Pillow version should be equal to `3.4.1`.

Otherwise when pulling latest version of your docker image and inside a new container:
```
root@44b3505cfecb:/# python -c 'import PIL; print(PIL.PILLOW_VERSION)'
2.6.1
```

In fact, almost all python dependencies required by odoo are not using the right version.

Upgrading Pillow to version `3.4.1` as stated in requirements solved our problem but we have to do it inside each container.

**Comment by azawawi** [comment]
@Fenkiou Just curious, what was the problem that the Pillow upgrade fixed and how did you fix it?

**Comment by steenzout** [comment]
and which version (or after what version) needed the fix?

**Comment by Fenkiou** [comment]
Well, we have a form input (website side) to upload an image and used Pillow to check validity of the data.

If I remember well (it was a colleague that encountered the issue), the error was IOError image not recognized or something like that.

After installing `Pillow==3.4.1`(one required by odoo) the error was gone.

**Comment by steenzout** [comment]
I meant Odoo version.

**Comment by Fenkiou** [comment]
Oh sorry, version 10.0

**Comment by steenzout** [comment]
@Fenkiou yes but it could affect older versions. :)

thank you!

**Comment by Fenkiou** [comment]
Absolutely, in fact the version of Pillow installed is even prior to the one required by odoo 9.0, didn't look in this container running 9.0 but I guess it's not up to date too.

**Comment by steenzout** [comment]
guessing here but Odoo gets installed in the container using a `.deb` package.

I'm not seeing how the `requirements.txt` gets used (which may be the reason why it's wrong from the start).

it seems to get this right the file for each version/date/commithash needs to be added to setup the python environment with the correct dependencies (`git clone`? `pip install -e ...@commithash`?).
if you have your own custom `Dockerfile` I guess it's easier to just add the `requirements.txt` with the exact dependencies+version and update the container's environment.

**Comment by Fenkiou** [comment]
I'm pretty sure you're right, I thought the same.

I don't know how their build process works (to make the .deb), but I think the problem should appear too on instance using the [.deb package](https://www.odoo.com/documentation/10.0/setup/install.html#deb) (not container, real instance). I'll check that tomorrow as we'll make production instance without Docker.

We don't have a custom image right now. We just use Docker to make demo instances.

**Comment by steenzout** [comment]
I've fixed the environment by adding the `requirements.txt` to my custom Dockerfile and patching the environment.
Building a new image and starting it shows the dependency/versions exactly as I expected.

I don't use the `.deb` for our production environment but I'd be curious to know your outcome.

**Comment by Fenkiou** [comment]
@steenzout So after our installation (not on Debian Jessie but Ubuntu Xenial, ), I checked the version of Pillow and guess what, it wasn't equal to the one to requirements.txt, it was the version `3.1.2` if I remember well (should have written it down).

I don't know if it would be different on Debian Jessie thought.

**Comment by steenzout** [comment]
@Fenkiou, sorry I should have known better.

The debian package obviously refers to the Python packages debian packages names so it will install what `Debian` or `Ubuntu` provide as latest versions.

e.g.
```
$ dpkg --info odoo_10.0.20170101_all.deb 
(...)
Depends: adduser, node-less, postgresql-client, python, python-babel, python-dateutil, python-decorator, python-docutils, python-feedparser, python-imaging, python-jinja2, python-ldap, python-libxslt1, python-lxml, python-mako, python-mock, python-openid, python-passlib, python-psutil, python-psycopg2, python-pychart, python-pydot, python-pyparsing, python-pypdf, python-reportlab, python-requests, python-suds, python-tz, python-vatnumber, python-vobject, python-werkzeug, python-xlsxwriter, python-xlwt, python-yaml
 Recommends: postgresql, python-gevent
```

I went for another path: `virtualenv` + `git clone` for Odoo [depth 1 and specific commit hash] + `pip install` for Odoo dependencies + `pip install` for the add-ons dependencies.
This gave me and my colleagues the exact environment on our laptops, containers (after I patched it) and servers.
At the time, it was a bit of work and I had to use a mix of Ansible playbooks, docker tools and bash scripts to manage to get this all in sync but now I can see it was worth the time. :)

out of curiosity, you managed to get a `wkthmltox` version `0.12.1` on Xenial?
did you build from source?

I don't think I managed to get the debian package to install on xenial and had to use `0.12.4` which is the only reason why I haven't moved to `16.04` on the servers running `Ubuntu`.

**Comment by steenzout** [comment]
@Fenkiou if you wish we can continue this thread on [Twitter](https://twitter.com/steenzout).

**Comment by Fenkiou** [comment]
@steenzout well odoo guys are doing it wrong.

If odoo require a specific version of a python package, this version should be installed, not the one coming with the distro. Otherwise this is an open door to strange behavior or even bugs because dependencies are not met.

**Comment by jaredkipe** [comment]
@steenzout @Fenkiou FWIW, you could take a look at my own version of this.  It starts with a newer version of Python, and builds in the requirements from source.

https://github.com/hibou-io/odoo-docker
https://hub.docker.com/r/hibou/odoo/

There are even nightlies using the '-latest' tags.

**Comment by Fenkiou** [comment]
@jaredkipe, thanks, that would be great but as [odoo/odoo#15718](https://github.com/odoo/odoo/pull/15718) is not merged, I'm still unable to use odoo docker images (without modification) with odoo addons installed with pip. But this is another issue.

**Comment by d-fence** [comment]
The image uses the Debian package and thus Debian python packages versions.
