### ISSUE TITLE
multiple ODOO instances on different port

### ISSUE THREAD

**Issue by BLukassen** [odoo/docker#113]
Running multiple ODOO instances with docker works, but the instance which in not linked to the port 8069 doesn't load the CSS definitions:

    $ docker run -p 8075:8069 --name odoo2 --link db:db -t odoo

When I open it in the browser like 'http://address.of.server:8075',
I get the ODOO page without CSS. Means, then CSS is not supplied
http://address.of.server:8075/web/content/326-372b744/web.assets_frontend.0.css
isn't sent from the server.

Which settings are missing?

**Comment by Haradrim** [comment]
I'm having the same problem not sure if I'm missing something or if it's something with the image.

**Comment by thomas15v** [comment]
The problem is that Odoo also has a filestore. You should mount this location `/var/lib/odoo` between the Odoo instances.

**Comment by BLukassen** [comment]
Do you mean:

    $ docker run -v /var/lib/odoo -p 8069:8069 --name odoo --link db:db -t odoo
    $ docker run --volumes-from odoo -p 8075:8069 --name odoo2 --link db:db -t odoo

Or do you mean something else?

**Comment by thomas15v** [comment]
`--volumes-from odoo` should do the trick I guess. When I experimented with this I did use a docker volume with docker-compose and a nginx proxy to proxy pass to different servers. The performance increase wasn't really noticeable. In fact I think that setting the workers in odoo on 5 would have had the same result.

In case of literary running 2 diffrent odoo instances (or more) on the same server with docker, we find it easier to just launch another db container (postgres only uses around 150mb ram). If you use docker-compose for example. You could just set the bind port differently in the [compose](https://github.com/thomas15v/odoo_docker/tree/master/docker_compose_overwrite_config) files and have 2 separate folders for the compose configuration. Like:

```
.
├── odoo1
│   ├── docker-compose.yml
│   └── odoo.conf
└── odoo2
    ├── docker-compose.yml
    └── odoo.conf
```

**Comment by d-fence** [comment]
seems solved
