### ISSUE TITLE
Dockerfile doesn't take latest build

### ISSUE THREAD

**Issue by livingdeadfr** [odoo/docker#117]
Hi,

Checking the code in the dockerfile for Odoo 10. I saw that the release date is hardcoded in the file.

So when pulling the latest release, it doesn't take the last nightly build but the build from the 20170207.

Can you fix it or explain why it is so ?

Regards

David

**Comment by thomas15v** [comment]
I guess the docker image makes use of stable builds. It also annoys me, I rather have `latest` being the latest code and having the ability to use `20170207` as a tag for example.

**Comment by steenzout** [comment]
@thomas15v and @livingdeadfr you can build any Odoo docker image and tag to your wishes.

look at https://hub.docker.com/r/steenzout/odoo/tags/ .

feel free to fork [my](https://github.com/steenzout/docker-odoo) repo and build whatever tags you need.
I made a [PR](https://github.com/odoo/docker/pull/93) but it got rejected so...

note: you should never use `latest` on a production environment; you should always use a version/timestamp tag and that's one of the reasons I created my own repo.

**Comment by thomas15v** [comment]
@steenzout that's what we do, we have our own docker repo and tag the images like this `odoo/<customer>:latest`. But the latest tag would be  useful for testing. I got a script on my build server that tries initializing my modules with the latest odoo. If the views don't crash, it's usually oke. But I kinda gave up on it, since it takes months for the odoo image to be updated.

I think the fastest way to fix this. Is to merge odoo/docker with odoo/odoo and generate images from the source instead of installing it from a debian file. That way it can also be connected with docker hub [properly](https://docs.docker.com/docker-hub/builds/#create-an-automated-build).

**Comment by steenzout** [comment]
@thomas15v I think could pull what you are asking for but I'd just need to be sure exactly what your idea is.
if you are interested ping me on Twitter (@steenzout as well).

**Comment by thomas15v** [comment]
@steenzout I am not so good with Twitter. But I just readed through the documentation of official docker images and what I proposed wouldn't work anyway. Apparently official images need to follow a release candidate kind of structure what would make it impossible to automate the `latest` to have the master branch code. 

My Idea was basically to have the Dockerfile sitting on odoo/odoo. And use docker hub to automatically build the image with the following mappings:
![image](https://user-images.githubusercontent.com/2163941/28662763-95c0b73a-72bb-11e7-8f31-3345cd02206f.png)

**Comment by anassahmed** [comment]
@thomas15v Everything can be automated with CI these days. We use Gitlab CI in our company and we generate images for our code on daily-basis (or with every merge request).

**Comment by odony** [comment]
Just updated at f432264ad15ce8e3326f281394e1900eb9d1c903, sorry for the delay! Pushed to official-images via docker-library/official-images#3335
Do not hesitate to ping @sle-odoo when you'd like an update of the releases ;-)

**Comment by anassahmed** [comment]
I would like this issue to be reopened for the suggestion to offer nightly tags alongside the image odoo version. as @thomas15v suggested, it would be the same as the debian package versioning that you use inside the docker container after all: `odoo:10.0.20170815` and `odoo:8.0.20170815` ... etc.

This would help us target a specific nightly version (even if the docker images isn't released every night) and narrow down issues if they arisen!

@odony @sle-odoo ping!
