### ISSUE TITLE
ppc64le dockerhub images

### ISSUE THREAD

**Issue by vaibhavsood** [odoo/docker#123]
Hi, I'm looking to enable docker containers for packages like odoo for multiple architectures on dockerhub, starting off with a focus on ppc64le. Wanted to check on the work that will be involved to do that

I have locally been able to successfully test ppc64le changes to the dockerfiles in this repo - changes for enabling additional arch would be minimum.

Would like to know how a multi-arch image for this can be initiated? The official images have this method for enabling multi-arch : https://github.com/docker-library/official-images#multiple-architectures, however this repo isnt an official image yet. Would the first step be to make this an official image or are there any other ways the dockerhub odoo image can be enabled for ppc64le?

**Comment by d-fence** [comment]
Support for arm64v8 was removed at docker-library/official-images@0a02e46
I think that ppc64le will suffer of the same problem.
