### ISSUE TITLE
Odoo 11 does not resolve assets

### ISSUE THREAD

**Issue by davidgomezq** [odoo/docker#128]
All directories **/static** modules are not resolved by the web server.

<img width="1920" alt="error" src="https://user-images.githubusercontent.com/560885/31663871-ab79735a-b343-11e7-8b46-aaaf423e4ecc.png">

**Comment by miguelparaiso** [comment]
Same here with a fresh installation of Odoo 11 with latest dockerfile.

**Comment by davidgomezq** [comment]
Solved. I forgot to add the new addons route from version 11 to odoo.conf

**Comment by thomas15v** [comment]
@davidgomezq, apparently you don't need to add "/usr/lib/python3/dist-packages/odoo/addons" or anything similar. Odoo 11 adds it's by itself. However I noticed odoo can not stand empty addons folders anymore.

**Comment by davidgomezq** [comment]
Thanks for the info @thomas15v

**Comment by lekhnath** [comment]
Empty addons directory was the source of all problems I encountered while trying to use odoo v11. Thanks a lot @thomas15v for sharing useful information.
