### ISSUE TITLE
Normalize database connection parameters

### ISSUE THREAD

**Issue by cecton** [odoo/docker#13]
Since Odoo 8.0 is a bit... complicated about the connection variables, I suggest we could "normalize" the connection parameter to set the `--db_*` argument _AND_ `PG*` env variables to make sure all the situations are covered.
### Current Priorities
-  `--db_host`, then `PGHOST`, ... (then localhost or /run/postgresql)
-  `--db_port`, then `PGPORT`, ... (5432)
-  `--db_user`, then `LOGNAME`, then die
-  `--db_password`, then `PGPASSWORD`

During a backup on Odoo 8.0, it's a bit different...
-  `--db_host`, then `PGHOST`, ... (then localhost or /run/postgresql)
-  `--db_port`, then `PGPORT`, ... (5432)
-  `--db_user`, then `LOGNAME`, then die
-  `PGPASSWORD`, then `--db_password`, then none

**Comment by sle-odoo** [comment]
We've finally been bitten by this kind of things (see a3d207f2d49c3a0eb0e959fbf2cb33909c382a3f). I'm closing this as we now only use the --db* arguments in the Docker file but we have opened a task to clarify and fix these issues upstream.

Regards
