### ISSUE TITLE
Odoo 10: no bootstrap in reports

### ISSUE THREAD

**Issue by giuliogatto** [odoo/docker#137]
Hi, I have no bootstrap in any report I am printing , both PDF and HTML.
I have checked the web.base.url parameter in Settings and its value is:
 http://127.0.0.1:8069

Anyone got bootstrap working for reports in Odoo 10 docker image?
Thanks

**Comment by thomas15v** [comment]
Do you mean that CSS classes won't load? Otherwise you could try to set `report.url` to `127.0.0.1:8069`.

**Comment by giuliogatto** [comment]
Hi, yes, the reports are bare HTML with no bootstrap styles. As a temporary solution I have added Bootstrap manually, but I'll try your suggestion asap. Thanks

**Comment by mikessoldier** [comment]
I have a similar problem.
A custom pdf report won't be properly bootstrapped unless other app like "Sales" is installed.

**Comment by d-fence** [comment]
Sorry to be so late. Odoo 10.0 is not more supported.
