### ISSUE TITLE
URGENT! Account tax affected fixed 12 days ago

### ISSUE THREAD

**Issue by phoenixsampras** [odoo/docker#141]
Please rebuild the container, since your using a commit from 22 days ago which contains the following problems in account tax (account.py)

https://github.com/odoo/odoo/commit/ce818f1f8f0557409f6d001c2c64446f9cdc3bdb#diff-a05f2edc3c15240bb7242d9bee80a14d

Many commits were rejects, and it is affecting tax calculations.

Please Rebuild ASAP HELP S.O.S.

**Comment by thomas15v** [comment]
Hi @aleskinen,

If you don't want to wait you can use the following Dockerfile to quickly update odoo in the image:

```dockerfile
FROM odoo:11

USER root

RUN set -x; \
        curl -o odoo.deb -SL http://nightly.odoo.com/11.0/nightly/deb/odoo_11.0.latest_all.deb \
        && dpkg --force-depends -i odoo.deb \
        && rm odoo.deb

USER odoo
```

**Comment by phoenixsampras** [comment]
Thats what we did for around 100 containers, forcing us to leave the Official odoo docker, sadly :(

**Comment by d-fence** [comment]
Fixed here: https://github.com/docker-library/official-images/commit/1fc758aba1014ba8a4486884270e1d732107e1f5
Sorry for the delay
