### ISSUE TITLE
All images are broken

### ISSUE THREAD

**Issue by imetallica** [odoo/docker#146]
None of the images work out of the box. Odoo cannot run if it is not running as a root user, as there is an error with permissions.

The .less compiling doesn't work as well. Wanted to show the system to my boss but it's quite impossible at the moment.

**Comment by thomas15v** [comment]
Hi @imetallica, I can assure you that the images work fine. Obviously something is wrong in how you set it up.

First things first. Permissions between your host machine and the container can be confusing. For example the user id's are different. The odoo user in the image has id 104, so you could chown folders to user 104. You also can give odoo permission by enabling read to the others group on your files (this is what I do).

Another thing I highly recommend is to use docker-compose with the images. This will ensure everything is correctly setup. You can find some examples [here](https://github.com/thomas15v/odoo_docker) (these are for odoo 10).

**Comment by imetallica** [comment]
@thomas15v thanks for the response, actually I'm using docker-compose with the configurations given in the docker hub page. It does not work for me.

**Comment by daniel2101** [comment]
You are use a backup?

If you use a backup of database the images don't show because its was saved in a folder. The backup must be created in zip format using odoo database manager.

**Comment by d-fence** [comment]
Cannot reproduce
