### ISSUE TITLE
[11.0] Docker for odoo11 enterprise

### ISSUE THREAD

**Issue by AlbatozK** [odoo/docker#148]
There's a changes in odoo web module, They add web.js_tests_assets since 10 Nov 2017
and in enterprise repo in web_gantt module also inherit from that one.

So there's 2 solution
1. Clone enterprise branch 11.0 only from commit earlier than 10Nov2017
2. Use newer odoo.deb image (Recommended)

**Comment by d-fence** [comment]
Already fixed
