### ISSUE TITLE
SMTP config options have no effect

### ISSUE THREAD

**Issue by stevevega** [odoo/docker#150]
I'm trying to setup the smtp values in the odoo.conf, this values are found in the example config file in this repo:
```
; smtp_password = False
; smtp_port = 25
; smtp_server = localhost
; smtp_ssl = False
; smtp_user = False
```

However, if I uncomment this lines and change them to a valid smtp server, when I start the container and check the config it still has the default values. Is there something I'm missing?

**Comment by d-fence** [comment]
Already answered
