### ISSUE TITLE
Style error immediately after installation

### ISSUE THREAD

**Issue by zenny** [odoo/docker#151]
Hi,

As soon as the latest odoo docker image was up and setup went as it should, the entire odoo page was garbled with style error:

```
**Style error**

The style compilation failed, see the error below. Your recent actions may be the cause, please try reverting the changes you made.

(b'', b'')This error occured while compiling the bundle 'web.assets_common' containing:
    - /web/static/lib/bootstrap/less/variables.less
    - /web/static/lib/bootstrap/less/mixins/vendor-prefixes.less
    - /web/static/lib/bootstrap/less/mixins/buttons.less
    - /web/static/lib/bootstrap/less/mixins/clearfix.less
    - /web/static/lib/bootstrap/less/mixins/size.less
    - /web/static/src/less/variables.less
    - /web/static/src/less/utils.less
    - /web_editor/static/src/less/web_editor.variables.less
    - /web/static/lib/bootstrap-datetimepicker/src/less/_bootstrap-datetimepicker.less
    - /web/static/src/less/fonts.less
    - /web/static/src/less/navbar.less
    - /web/static/src/less/mimetypes.less
    - /web/static/src/less/modal.less
    - /web/static/src/less/animation.less
    - /web/static/src/less/rainbow.less
    - /web/static/src/less/datepicker.less
    - /web_planner/static/src/less/web_planner_common.less
    - /web_tour/static/src/less/tip.less
    - /web_tour/static/src/less/keyframes.less
```

'node-clean-css' and 'node-less' packages were installed (https://www.odoo.com/forum/help-1/question/solved-odoo-9-which-lib-is-missing-to-resolve-this-error-91050). 
```
root@odoo:/# dpkg -l | grep ii | grep node
ii  node-clean-css                1.0.12-2                       all          Node.js module for minifying CSS files
ii  node-commander                2.4.0-1                        all          Complete solution for Node.js command-line interfaces
ii  node-less                     1.6.3~dfsg-2                   all          LESS CSS meta-language - compiler and Node module
ii  nodejs                        4.8.2~dfsg-1                   amd64        evented I/O for V8 javascript
```

Even soft-linking /usr/bin/nodejs to /usr/bin/node (https://github.com/odoo/odoo/issues/10050#issuecomment-168111542) didn't help either.

Inputs appreciated. Thanks!

Season's greetings and cheers,
/z

**Comment by AyaYousef** [comment]
I've the same issue here, in Odoo V11 in both Enterprise & Community Editions.

**Comment by Sortedgit** [comment]
Try upgrading your pip3
Using command: pip install --upgrade pip 
This will definitely solve your error. Hope it helps. Thank you.

**Comment by jbeficent** [comment]
See https://github.com/OCA/ansible-odoo/issues/72 for the final solution to the problem. Requires to change the default values in the odoo config file.
limit_memory_hard: 2684354560
limit_memory_soft: 2147483648

I think that this issue can now be closed.

**Comment by AyaYousef** [comment]
@jbeficent I have the same values in my configuration file and yet I have the same problem

**Comment by oosantana** [comment]
Try

sudo apt-get install nodejs
sudo apt-get install npm
sudo npm install -g less
sudo npm install -g less-plugin-clean-css
sudo ln -s /usr/local/bin/lessc /usr/bin/lessc
sudo ln -s /usr/bin/nodejs /usr/bin/node

Restar Odoo

**Comment by amirpadilla** [comment]
@jbeficent changing the memory limits does not solve the issue, it seems more like a less recompile the issue

**Comment by 1994jovial** [comment]
hi,

style error in odoo 11

Could not get content for /bs_hr_attendance/static/src/css/style.css defined in bundle 'web.assets_backend'.

**Comment by edibertk** [comment]
Try sudo pip3 install libsass==0.12.3 
sudo apt install python3-libsass
check requirement.txt to verify if they installed well.

**Comment by d-fence** [comment]
Already fixed. Odoo uses sass instead of less since 12.0.

**Comment by Rionz** [comment]
> Already fixed. Odoo uses sass instead of less since 12.0.

How you fix this. Thank you

**Comment by cuburt** [comment]
Im using odoo:12 image in 2021 and I still have the issue. What's the fix?

**Comment by tim-win** [comment]
@cuburt Could be this issue, I ran into something similar where my stylesheets were 404'ing shortly after install: https://github.com/odoo/docker/issues/369
