### ISSUE TITLE
Docker image root access

### ISSUE THREAD

**Issue by demogorgonz** [odoo/docker#154]
```
odoo@fcc4eec7806a:/$ su -
su: must be run from a terminal
```

Getting around restirctions : 

```
echo "import pty; pty.spawn('/bin/bash')" > /tmp/asdf.py
python3 /tmp/asdf.py
```

example : 

```
odoo@fcc4eec7806a:/$ echo "import pty; pty.spawn('/bin/bash')" > /tmp/asdf.py
odoo@fcc4eec7806a:/$ python3 /tmp/asdf.py
odoo@fcc4eec7806a:/$ su -
Password: 
```

Are we allowed to get root access within this image ? If so, are credentials documented ?

This issue is related to #153 to provide(install) more debugging tools on debian 9 odoo image.

**Comment by thomas15v** [comment]
Hi @demogorgonz ,

You can try the following commands to get root access in the container.

- docker exec -u root <container id> bash
- docker-compose exec --user root <container entry> bash

**Comment by gjae** [comment]
> Hi @demogorgonz ,
> 
> You can try the following commands to get root access in the container.
> 
> * docker exec -u root  bash
> * docker-compose exec --user root  bash

Here in 2021 year, your reply work me thanks!
