### ISSUE TITLE
Lost setup

### ISSUE THREAD

**Issue by kickfliph** [odoo/docker#155]
Hello There,

So I install the Odoo using the docker pull from your repository and it works fine, everything went smoothly good, but after installing and setting up everything in Odoo I needed to restart the server, nothing to do with docker, so after restart, I went to Odoo and I found that it didn't save anything that I did before, I lost all the initial setup, modules installed it was back to the beginning asking me for the user and password to setup the database and so, I follow the instructions as you posted[1] here the instrucctions that bassicly I used was:

Start a PostgreSQL server

$ docker run -d -e POSTGRES_USER=odoo -e POSTGRES_PASSWORD=mypassword --name db postgres:9.4 

* here the only thing that a change was the password and then,

Start an Odoo instance

$ docker run -p 8069:8069 --name odoo --link db:db -t odoo

So what I miss?, what I should do to for this not to happen again?

Thanks for all your help.

Regards,

[1] https://hub.docker.com/_/odoo/

**Comment by thomas15v** [comment]
Hi @kickfliph,

I would recommend using docker-compose. I got a repo with some example [files](https://github.com/thomas15v/odoo_docker).

I do not know what you did wrong, however running docker run twice should have caused this error:
> docker: Error response from daemon: Conflict. The container name "/odoo" is already in use by container "e07399b0590c061afd323a819f985e6749e3fb93b90f6450890897aa2e568007". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.

So this indicated that the container has been removed. The proper start, stop and restart commands are `docker start odoo` , `docker stop odoo` and `docker restart odoo`.

If your installation contained production critical data, you might want to look in `docker volume` to try to find your lost volume. The data should be stored in /var/lib/docker/volumes/<volume_id>/_data (you need root to read this folder).

**Comment by kickfliph** [comment]
Hi @thomas15v,
Thanks for your quick response. Yes, for sure is something that I doing wrong, I use the docker-compose and my .yml[1] looks very similar to those ones that you link me up, so the Odoor docker works fine but the PostgreSQL keep saying "FATAL:  password authentication failed for user "odoo"" and on the other hand I found the volume path and in it the information, so how I solve this problem? and finally make Odoo works with the persistent data.

[1]version: '2'
services:
  web:
    image: odoo:latest
    links:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
  db:
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data:
  odoo-db-data:

Regards,

**Comment by thomas15v** [comment]
@kickfliph 

Your compose file looks oké, although it's not necessary to overwrite those volumes. Docker will automatically create them and assign an ID to them. This is done with the volume tag in the [Dockerfile](https://github.com/docker-library/postgres/blob/3001d13fcac68cf9f8b0217eafdad8e83c41907c/9.4/Dockerfile#L127).

As for why it isn't working,I think your postgres volume is not assigned properly. You should use the following I think:
````yml
...
volumes:
- odoo-db-data:/var/lib/postgresql/data/pgdata
...
````

**Comment by kickfliph** [comment]
Hello there,
thanks to @thomas15v who help me out with this problem, so I point the volume to the path and now I have the Odoo working perfectly. Thanks.
