### ISSUE TITLE
Docker remove

### ISSUE THREAD

**Issue by kickfliph** [odoo/docker#156]
Hello everyone,

So I have my Odoo working perfectly I follow the manual in dockerhub[1], I'm using the docker-compose .yml, but as newbie, I have a few questions:

*.- If a do a `docker rm <docker-id>` to the Odoo and PostgreSQL containers I will lose all data? 
*.- If a want to have more than one database in the same Postgresql container changing the .yml parameters will be enough?

Thanks for all your help.

[1]https://hub.docker.com/_/odoo/

**Comment by thomas15v** [comment]
* Depends, if you do `docker rm -v <container-id>` or `docker-compose rm <container-id>` you will lose data. However if you did delete the container it will be fairly difficult to restore the container with the old volumes. Check out docker volume [documentation](https://docs.docker.com/engine/admin/volumes/volumes/).
* You do not need to change yml parameters in your docker-compose to add new databases. Creating a new database with  `/web/database/manager` will suffice.

**Comment by kickfliph** [comment]
Thanks Again,
