### ISSUE TITLE
Odoo 11 Community edition

### ISSUE THREAD

**Issue by kickfliph** [odoo/docker#157]
Happy holidays to everyone,

So I have been around Odoo for a while since it begins, but what a have done so far with Odoo it just install and configure it, now I'm ready to have it work for my own company, I read a lot of what and how is the best way for me to make it work, but I still have a few questions hopping find the answers here.

*.- Can I use the community version for my starting company? 
*.- The community version contains the basic needs for my starting company?
*.- In the future, if I need to migrate to the full version, how hard will be to do this?
*.- I know that the accounting module in the community version it's limited, how limited is this will be for me in the beginning?

I set up a community version that it's running in AWS using docker pull from your Dockhub

The business area of the company its e-commerce  

Thank you for all your help.

**Comment by thomas15v** [comment]
- That would be a yes I think.
- Depends what you need? If you need subscriptions that would be no.
- Yes, since odoo 10 you can easily upgrade by installing `web_enterprise` module.
- Not sure what you mean, the accounting module in enterprise only adds a few features.

**Comment by d-fence** [comment]
Answered
