### ISSUE TITLE
Odoo 10 not showing images

### ISSUE THREAD

**Issue by navarromiguel** [odoo/docker#158]
Since I started to work with Odoo-docker, I find problems with images of the website, they doesn't appear...
This not occurs always but, when i run a new Odoo container with db-filter i.e. it occurs and, in some cases, static files doesn't load properly (css, js, imgs...) and I have to re-run with other container or restart postgres container, etc.

![image](https://user-images.githubusercontent.com/6492375/34669681-24809466-f473-11e7-9a03-4566021c33b5.png)

**Comment by d-fence** [comment]
Sorry for the late answer but 10.0 is not more supported.
Please open a new issue if the problem still happens in other versions.
