### ISSUE TITLE
Slow PDF Generation

### ISSUE THREAD

**Issue by open7c** [odoo/docker#160]
Latest Odoo Docker Version.

The Generation of a simple PDF (Invoices without payment) takes 2 Minutes.

Is there a way optimise this?

T.i.A.

**Comment by open7c** [comment]
Works now after we created the Systemparameter "report.url=http://127.0.0.1:8069"

**Comment by Floggedhorse** [comment]
OMG! - I've never experience a report created so fast, thank you

**Comment by BecaOdoo** [comment]
waooooooooooooooooo  THIS WORKED FOR ME with the reports, but when loading or recording an action it's still slow

**Comment by Desarrolladorpython03** [comment]
> Works now after we created the Systemparameter "report.url=http://127.0.0.1:8069"
Thank you so much! it works!
