### ISSUE TITLE
Not 100% persistent

### ISSUE THREAD

**Issue by open7c** [odoo/docker#162]
i.e. when a user uploads an avatar in his settings this image has gone after an update. what directories should be mounted to the host?

**Comment by veivaa** [comment]
Odoo container exposes two volumes (≈directories): one for filestore and one for add-on modules. In your case you need to specify persistency for the filestore in container path /var/lib/odoo to keep the files after container recreation.

You can find an example of Odoo installation in Docker container with persistent volume in Unkkuri's blog at https://unkkuri.com/blog/unkkuri-blog-1/post/install-odoo-version-11-in-docker-container-21. 

You can find the volume description in Dockerfile line starting with VOLUME. This line tells what paths are exposed as volumes.
`VOLUME ["/var/lib/odoo", "/mnt/extra-addons"]
