### ISSUE TITLE
Can't print documents: Uncaught SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by pokapow** [odoo/docker#163]
In a fresh Docker install, with Odoo 11, I can't print any document, invoice or whatever. There is a time of 1 minutes charging, and then this error:
```
Error:
Uncaught SyntaxError: Unexpected end of JSON input

https://exemple.fr/web#id=1&view_type=form&model=account.invoice&menu_id=123&action=198:1
Retraçage :
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at HTMLIFrameElement.<anonymous> (https://exemple.fr/web/content/369-daca186/web.assets_common.js:3843:379)
    at HTMLIFrameElement.dispatch (https://exemple.fr/web/content/369-daca186/web.assets_common.js:892:451)
    at HTMLIFrameElement.elemData.handle (https://exemple.fr/web/content/369-daca186/web.assets_common.js:865:173)
```

The URL here is OK. I can't find the "the web.base.url paramter in Settings>>Parameters>> Sytem Parameters" as say in this thread: https://www.odoo.com/fr_FR/forum/aide-1/question/openerp-client-error-uncaught-syntaxerror-unexpected-end-of-input-what-does-that-mean-62326

wkhtmltopdf seems to be install in the docker container, because when I enter the command "wkhtmltopdf" inside the container, the system recognizes it.

I don't find any pertinent logs about it. Where can I find good debug log ?

**Comment by pokapow** [comment]
Problem solve: I just remove the upstream parameter in my nginx reverse proxy ... Spent 3h just for that.

**Comment by libukoshy** [comment]
Hi,
I am facing same issue in odoo 10 community edition,
I am using webpdfpreview module for print.if I uninstalll this module error gone .
How I can solve this issue?

**Comment by Br3mah** [comment]
Hi,
Have you also tried to install WKITPDFTOHTML or WERKZEUG

**Comment by save85** [comment]
Hi, 

I have the same problem. which was the nginx upstream parameter to remove?
Thanks
