### ISSUE TITLE
/var/lib/odoo - ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by Reechee88** [odoo/docker#172]
Hi guys,

I had a hard time figuring out why odoo serves ERR_EMPTY_RESPONSE after creating my docker containers. Here is my docker-compose.yml:

`
version: '2'
services:
  web:
    image: odoo:11.0
    container_name: web
    depends_on:
      - db
    restart: always
    ports:
      - "8069:8069"
    volumes:
      - ./web_data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./config:/etc/odoo

  db:
    image: postgres:9.4
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./database:/var/lib/postgresql/data/pgdata
`

When I don't use the attached volume for /var/lib/odoo, it works fine. Whenever I attach the volume, it serves empty reponse. 
I have check the access rights for the folder, it is fine.

What the hell is the problem with this mounting? This is the same that is stated on your documentation!

Thanks for help.

Have a nice day,
Richard

**Comment by zakanybalazs** [comment]
I have the same problem... Help would be appreciated

**Comment by mountkin** [comment]
It's a permission problem. `chown -R /var/lib/odoo` fixed the problem!
Curious why there's no error log when directory permission is insufficient.

**Comment by weeger** [comment]
Thank you @mountkin but when do you execute this command ? In host or in container ?
I try to launch odoo with docker-compose and to have it initilized but it does not start when I share the `/var/lib/odoo` volume.

Thanks

**Comment by quangthe** [comment]
@weeger  When you mount volume, please set permission 777 to folder in host: 
In my case: ~/odoo/odoo:/var/lib/odoo -v ~/odoo/extra-addons:/mnt/extra-addons

Then I set: 
$ chmod -R 777 ~/odoo
Stop and remove existing odoo container. Then start new one. 

Hope it help!

**Comment by earth001** [comment]
In my case, I connect to the container
`docker exec -it -u root odoo_web bash `
Go to web dir:
`cd /var/lib/odoo/ `
And update the owner as @mountkin suggested:
`chown odoo:odoo . `
After that, the container starts to work ok.

**Comment by MaitreDede** [comment]
Hi,
In my case, it was my disk that had too many files and  could not create new session files on disk. In my case, session files were created faster than odoo cleanup

**Comment by d-fence** [comment]
solved

**Comment by suraj95** [comment]
I'm still facing this issue and I'm not even using Docker. Please help!

**Comment by herawais** [comment]
I faced same problem, the issue was the persistantVolume storage was full , i increased the capacity of PV and it worked,
i am using Odoo based on Kubernetes
