### ISSUE TITLE
Odoo cant import Watcher 10.0v (when he istalled)

### ISSUE THREAD

**Issue by advance** [odoo/docker#173]
Hello, guys. I think i read all tickets in internet for google 'Watcher odoo windows don`t work why who i am ad e.t.'
In real i use pip install watchdog, and in py file on desktop its work

> try:
>     import watchdog
>     from watchdog.observers import Observer
>     from watchdog.events import FileCreatedEvent, FileModifiedEvent, FileMovedEvent
> except ImportError:
>     watchdog = None
> print(watchdog)
> if watchdog:
>     print("'Well, its work") 
> ###its work
> else:
>     print("'watchdog' module not installed. Code autoreload feature is disabled")

But why odoo cant import them???
In odoo, import return nothing. 
Should i install it for odoo folder, or what??? 
Thank you, for responce.

**Comment by d-fence** [comment]
Fixed here: cec9d153fee90d
