### ISSUE TITLE
how to start a instance without demo data?

### ISSUE THREAD

**Issue by EternalTitan** [odoo/docker#175]
how to start a instance without demo data?

**Comment by sylnsr** [comment]
What version? Using v10 `--without-demo=all` should work (tested myself with rel 20180809)
Found that in this book https://play.google.com/store/books/details?id=Kv7fDAAAQBAJ

The book actually just specifies `--without-demo` .. however Odoo complained that a param was required so, following Odoo paradigms, it was easy enough to figure out that `=all` should be added.

**Comment by d-fence** [comment]
Answered
