### ISSUE TITLE
odoo 10 issue

### ISSUE THREAD

**Issue by tbs575** [odoo/docker#176]
when I restore my database, and access my odoo by chrome. I got error:
"Could not get content for /web_enterprise/static/src/less/variables.less defined in bundle 'web.assets_common'.
how to fix it? thanks

**Comment by jleal-pnet** [comment]
i have the same problem, know someone how to fix it?

**Comment by d-fence** [comment]
Need more info to try to reproduce

**Comment by d-fence** [comment]
Sorry to say a bit later that Odoo 10 is not supported anymore
