### ISSUE TITLE
not loading styles

### ISSUE THREAD

**Issue by bluemix** [odoo/docker#179]
I am using docker image of `Odoo 11.0-20180122 (Community Edition)`.

I wanted to use styles, e.g.,
```
<xpath expr=".">
    <link rel="stylesheet" href="/module_name/static/src/less/styles.less"/>
</xpath>
```

but, they didn't load.
besides, every module in the `addons` folder that uses this method, it's style 
didn't load.

**Comment by robwithhair** [comment]
I had this.  It's probably a python error causing the static file server not to run.  Check the logs maybe?

**Comment by bluemix** [comment]
I found a clue: every time I use and work with Odoo JSON-RPC, the styling breaks.
So, I keep removing and recreating the same docker container every time I finish my RPC things.

**Comment by mohamedsaad306** [comment]
if you are mapping addons to a folder on the host machine that is hosting the container try to check and change the owner of the addons inside to the container owner. it worked for me  image of odoo 10.

**Comment by robwithhair** [comment]
I think this is due to python compile error on startup.  Check the logs for clues.

**Comment by d-fence** [comment]
Solved

**Comment by mmorenoxumak** [comment]
How did you solve it? @d-fence
