### ISSUE TITLE
Runbot Docker File and image

### ISSUE THREAD

**Issue by online-sanaullah** [odoo/docker#182]
Hi, 

There is no official docker image for the runbot that is capable of running/building/testing Odoo11. It will be highly appreciated if runbot images are also included in this repository. This will make it easier for odoo developers to deploy their own runbot with ease.

Regards,
Sanaullah

**Comment by d-fence** [comment]
Hello, the runbot is an internal tool that we share with the community. There is no plan to create a Docker image of it as we have no use case of that. I'm sorry.
