### ISSUE TITLE
Outdated Docker image with major issue

### ISSUE THREAD

**Issue by Maxim-Mazurok** [odoo/docker#184]
I've installed odoo via docker today.
When creating new Customer, after filling all the data, I've clicked on "sms" icon just from curiosity about what is it.
I've got the error, described in issue https://github.com/odoo/odoo/issues/22433 and have lost all of filled data, because it was unsaved and modal window closed after error occurred. What is strange here, is that I'm unable to reproduce this exact behavior anymore. Modal window stays opened. Also, I've just found that the record was saved somehow.. Maybe there is an "autosave" feature in Odoo software? IDK. Anyway, this is not related.

I think that it's really important to apply this patch from commit https://github.com/odoo/odoo/commit/16c6b520fb901491e09cd3b86ac5b49171014892 to nightly image of odoo v11.0 on docker.

---

**Workaround**, while it's not applied to docker image:
1. Login as root into your docker container:
```bash
docker exec -u 0 -it odoo bash
```
2. Update packages list:
```bash
apt update
```
3. Install `vim`, or any other text editor of your preference (`vi`, `nano`, etc.):
```bash
apt install vim
```
4. Open file `send_sms.py` in text editor: 
```bash 
vim /usr/lib/python3/dist-packages/odoo/addons/sms/wizard/send_sms.py
```
5. On line 73, find:
```python
number = self._sms_sanitization(partner, self.env.context('field_name') or default_field_name)
```
and replace it with:
```python
number = self._sms_sanitization(partner, self.env.context.get('field_name') or default_field_name)
```
6. It might be a good idea to restart odoo:
```bash
service odoo restart
```

---

Thanks in advance.

**Comment by d-fence** [comment]
fixed
