### ISSUE TITLE
New Github project to provide "batteries included" dockerized Odoo server

### ISSUE THREAD

**Issue by greaber** [odoo/docker#197]
We have been using Odoo for the last few months at my company, and I have been responsible for setting up an running the server.  I chose to use the docker image for this, which has generally worked out quite well, but I found there were still a lot of steps involved in getting a production Odoo server working that aren't well documented, to my knowledge.  I just made a repo containing the full system we are using and including a detailed README explaining everything you need to do to get set up.  I would be pleased if you guys take a look, let me know if you have any suggestions, and spread the word if you like what you see.  https://github.com/respeecher/auto-odoo

**Comment by thomas15v** [comment]
Looks neat, although I disagree with a few things:

- CertBot is running outside the docker infrastructure.
- The backup solution can be dockerized as well. (Using alpine with crond and docker client)
- It uses systemd while you can simple add `restart: always` to a container to make it start with docker.

This is a simplified version of what I use at [work](https://gist.github.com/thomas15v/326c0b23aa6c3eab53cc6c0a6c12156d). It doesn't have a dedicated backup feature yet tho, but mostly we solve that by having VM snapshots. But I agree that is not that flexible.

**Comment by greaber** [comment]
Thanks for taking a look, Thomas.

I agree that more things could be dockerized although using cron for backups and certbot works all right, and using docker-based cron would probably be slightly more complicated.  It seems like a matter of taste, or a design decision that doesn't make a big difference either way.

I think systemd is necessary to make the system start automatically at boot, right?  Then, given that we are using it, restarting can easily be handled either by systemd or by docker.  I guess there is a difference in behavior in that docker could restart a single container, while systemd would only restart the whole docker service, right?  Probably restarting will work fine either way, I guess, though if anything restarting the whole service would seem safer but slower.

**Comment by thomas15v** [comment]
> I think systemd is necessary to make the system start automatically at boot, right? 

No, docker is already in systemd or upstart. If you give a container the correct restart policies it will start as soon docker is ready. Although this only works if you don't remove containers to shutdown. 
(`docker-compose stop/start/restart`)

> using docker-based cron would probably be slightly more complicated.

I agree on that. However I also like the idea that I can take a docker-compose to another machine and install it without having to worry about other things. It also makes documentation on projects fairly simple.

**Comment by greaber** [comment]
> No, docker is already in systemd or upstart. If you give a container the correct restart policies it will start as soon docker is ready. 

Interesting, I didn't realize that docker had this capability.  It does seem that this could be a bit less reliable than systemd though since it depends on the containers not somehow getting lost, but maybe this is just paranoia.

I guess I agree that further dockerization has some real advantages in making it easy for people to set up Odoo, but it is likely not something I will get around to changing.

Anyway, we can close this issue I guess, but I do think it would be nice if new Odoo users were pointed to some more complete instructions for setting it up since it took me some non-trivial time to work this out, and it would be even more difficult for someone without much experience administering Linux servers.

**Comment by d-fence** [comment]
Thanks for the useful link and the time you spend for that documentation.
I 'm closing it as it's not a real issue.
