### ISSUE TITLE
404 error when using http://localhost:8069/xmlrpc/2/common

### ISSUE THREAD

**Issue by totoskul** [odoo/docker#205]
Hi. 

I just installed basically the docker-compose for odoo for docker. 

The web app woks great, but when I try to use the api from a rest client, I always get 404 pages. 

Is it normal ?

**Comment by totoskul** [comment]
My bad I was using it wrong. 

a good article to test with postman : 

https://www.surekhatech.com/blog/working-with-odoo-web-services

**Comment by d-fence** [comment]
Seems solved
