### ISSUE TITLE
Session messed up... no x-forwarded-for

### ISSUE THREAD

**Issue by open7c** [odoo/docker#209]
Odoo 11.0-20180808 (Community Edition)

2 Persons are using Odoo.

Person A logs in... ok
Person B logs in... ok
After a few clicks Person B is logged in as Person A, and Person A gets "Invalid Session" or something and has to Logout, Person B has full Control over A's Account...

This happens on 3 different PCs.

Maybe it has to do with Session Handling or Cookies. In the Odoo Logfile i can see that the IP-Address of the Docker-Gateway is used instead of the Client:

> 2018-09-11 12:34:33,303 1 INFO odoo2 werkzeug: **172.17.0.1** - - [11/Sep/2018 12:34:33] "POST /longpolling/poll HTTP/1.1" 200 -

Odoo is called via an Apache Reverse Proxy, which sends the X-Forwarded-For Header with the Real Client IP-Address.

Or is there another Way to inject the Real Clients IP to Docker or Odoo? Tried everything like mod_rpaf, mod_remoteip, someone said to use --net=host but thats not possible on linked Containers...

A generic solution would be cool, maybe on the Docker Level so every Container gets automatically the Real Client IP.

**Comment by open7c** [comment]
Seems like this Project is dead. No one cares about Bugs with that kind of impact here.

Solved it by disabling the Apache Module cache_disk.

**Comment by d-fence** [comment]
solved, closing.
