### ISSUE TITLE
Odoo 12

### ISSUE THREAD

**Issue by lastalfriday** [odoo/docker#210]
Would it be possible to add an Odoo 12 image for testing and upgrading purposes?

**Comment by foutoucour** [comment]
We would be very interested also. Some clients are already asking to play with it.

Thank you team!

**Comment by bjoliveau** [comment]
+1 ;-)

**Comment by W360S** [comment]
voted 👍

**Comment by mannp** [comment]
Looking forward to upgrading my v11 docker to v12 :+1:

**Comment by phoenixsampras** [comment]
ODOO 12 is out, please build the docker ASAP!!

Thanks in advance!!

**Comment by Stefano-Pedretti** [comment]
:+1:

**Comment by W360S** [comment]
v12 is already come out https://github.com/odoo/odoo

**Comment by mannp** [comment]
Created a PR here https://github.com/odoo/docker/pull/215 my first one, so go easy.

My docker build is on docker hub for testing purposes only.

**Comment by fernandogbj** [comment]
Can you pass the installation and configuration data of Odoo 12 with Dockert and PostGes with Dockert?

**Comment by W360S** [comment]
@fernandogbj im using the latest one

**Comment by fernandogbj** [comment]
> @fernandogbj estoy usando la última

PostGres 11???

**Comment by wilk** [comment]
Solved with: https://github.com/odoo/odoo/issues/27447#issuecomment-427840100

**Comment by d-fence** [comment]
Docker image for Odoo 12 landed on the [hub](https://hub.docker.com/_/odoo/)
Enjoy
