### ISSUE TITLE
What about to have docker for earlier versions of Odoo?

### ISSUE THREAD

**Issue by akolpakov** [odoo/docker#213]
Sometimes customers use old versions of Odoo.

It would be useful to have docker for versions 7 and 8.

I can contribute if you don't mind.
https://github.com/akolpakov/odoo-7-docker

**Comment by d-fence** [comment]
Hello, I'm sorry to say that we only support the [3 latest versions](https://www.odoo.com/page/download) of Odoo.
So versions 7, 8 and 9 are now deprecated.
