### ISSUE TITLE
Odoo:12 comes as enteprise edition

### ISSUE THREAD

**Issue by Stefano-Pedretti** [odoo/docker#222]
Hi All,
I just upgraded our test environment to version 12 and I noticed that the pulling odoo:12 I get the enteprise edition. Previous version was pulling the community edition.

Is that expected?
How can I get the community edition instead?

Thanks

**Comment by francoisdelarbre** [comment]
Hello @Stefano-Pedretti , 
I faced the same issue. you just have to change the Odoo release in the dockerfile to a newer  one (e.g. 20181008 to 20181020 :`ENV ODOO_RELEASE 20181020`) and the corresponding checksum `&& echo '333624a80c11dd7fccf55c79ebd7a760e3b01d9c odoo.deb' | sha1sum -c - \.`

You can check my fork [https://github.com/francoisdelarbre/docker](url) or use the image built from it [https://hub.docker.com/r/francoisdelarbre/odoo/](url) until it is officially fixed.

**Comment by my1649** [comment]
> Hello @Stefano-Pedretti ,
> I faced the same issue. You just have to change the Odoo release in the dockerfile to a newer one (e.g. 20181008 to 20181020 :`ENV ODOO_RELEASE 20181020`) and the corresponding checksum `&& echo '333624a80c11dd7fccf55c79ebd7a760e3b01d9c odoo.deb' | sha1sum -c - \.`
> 
> You can check my fork [https://github.com/francoisdelarbre/docker](url) or use the image built from it [https://hub.docker.com/r/francoisdelarbre/odoo/](url) until it is officially fixed.

Hi @francoisdelarbre the links you provided are empty. No images, no information inside.

**Comment by francoisdelarbre** [comment]
Hi @Stefano-Pedretti ,
Yes, indeed, I mis encoded the urls, it's fixed now.

**Comment by measwel** [comment]
Please fix the official image so we can enjoy the community edition again.

**Comment by d-fence** [comment]
Fixed in Odoo that referenced Enterprise in Community
