### ISSUE TITLE
start docker-compose firsttime but show web login?

### ISSUE THREAD

**Issue by voratham** [odoo/docker#229]
I have the problem with odoo, When i start odoo by using docker-compose up via docker-compose.yml but every time and access http://localhost:8069  will show webpage login away. But my not still setting new database.

> version: "2"
services:
  db:
    container_name: db
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
  odoo11:
    container_name: odoo11
    image: odoo:11.0
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8072:8072"
    tty: true
    volumes:
      - ./addons:/mnt/extra-addons
      - ./config:/etc/odoo
      - ./log_odoo:/var/log/odoo
      - ./lib_odoo:/var/lib/odoo
volumes:
  db:
  odoo11:``

my docker version
docker version 18.09.0, build 4d60db4
docker-compose version 1.23.1, build b02f1306

**Comment by foutoucour** [comment]
Hello @voratham 

Could you share what is present in `./config`? Do you have a `odoo.conf` file in it with a setup for the parameter `db_name`?
If so, odoo create by default a database with the name.

Is it the case?

Jordi

**Comment by d-fence** [comment]
I close it as there was no answer in last two years. Feel free to re-open if the issue still exists.
