### ISSUE TITLE
Problems mounting custom addons

### ISSUE THREAD

**Issue by chochichaga** [odoo/docker#232]
Hi,
I'm new to this and I do not know if I'm doing the right steps. The first thing I did was create a folder / addons, then inside this folder I created another folder / addons / celes_app, and within this last folder I have all my files (__init__.py, __manifest__.py, etc).
Then I create the following containers:

`docker run -d -e POSTGRES_USER=odoo -e POSTGRES_PASSWORD=odoo -e POSTGRES_DB=postgres --name db postgres:10 `

`docker run -v /addons:/mnt/extra-addons -p 8069:8069 --name odoo --link db:db -t odoo`

By doing so, the container is successfully created. I open a browser and enter port 8069, it asks me to create a new database, and when I create it I get the following error:

`2018-11-28 23:45:46,936 1 INFO None odoo.service.db: Create database `Prueba`. 
2018-11-28 23:45:47,402 1 ERROR None odoo.service.db: CREATE DATABASE failed: 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/service/db.py", line 58, in _initialize_db
    odoo.modules.db.initialize(cr)
  File "/usr/lib/python3/dist-packages/odoo/modules/db.py", line 34, in initialize
    for i in odoo.modules.get_modules():
  File "/usr/lib/python3/dist-packages/odoo/modules/module.py", line 408, in get_modules
    plist.extend(listdir(ad))
  File "/usr/lib/python3/dist-packages/odoo/modules/module.py", line 401, in listdir
    for it in os.listdir(dir)
PermissionError: [Errno 13] Permission denied: '/mnt/extra-addons'
2018-11-28 23:45:47,422 1 ERROR None odoo.modules.loading: Database Prueba not initialized, you can force it with `-i base` 
2018-11-28 23:45:47,485 1 INFO Prueba odoo.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 1 connections to 'dbname=Prueba user=odoo password=xxxx host=172.17.0.2 port=5432 sslmode=prefer'
`

Someone could help me?
Thank you

**Comment by salfredogonzalez** [comment]
I would recommend that you give a try to do it this way instead, if you have the container file in your folder, <docker-compose.yml> just run: "docker-compose up" or docker-compose up -d" for daemon.
in the file provided for Odoo it would read the folder "o_addons" for Odoo 11, in Odoo 10 its used "addons" folder. I didnt see the version that you are using but i hope this can help.

**Comment by fractalf** [comment]
Using docker-compose like @salfredogonzalez said is definetly the easiest way to set this up. Then you define alle those command line options in the docker compose yml file which is much easier.  

Take a look at the example at the bottom here https://docs.docker.com/samples/library/odoo/ and you should be able to do this easily

**Comment by Lodeiro0001** [comment]
This is because, although in the documentation it is said that the route / mnt / extra-addons can be used for our custom modules, I suppose that by mistake this is not added in the Odoo configuration inside the container.

## Solution:
- Connect to the container by terminal and enter / etc / odoo /
- Create a new configuration file, which will be complementary to the existing default configuration
```bash
sudo nano odoo.conf
```
- We paste the following and save:
```
[options]
addons_path = / mnt / extra-addons
```

Once the container has been restarted, we can use the route without problem.

**Comment by fractalf** [comment]
@Lodeiro0001 The correct way to use this is to have the two files **odoo.conf** and **entrypoint.sh** from here https://github.com/odoo/docker/tree/master/12.0 in the same directory as your **docker-compose.yml** file

**Comment by chrisdev2018** [comment]
@Lodeiro0001 thanks.
I had same problem and your  solution was the good one

**Comment by d-fence** [comment]
Solved

**Comment by Tarikol-Islam** [comment]
I Have 3 different folder with addons, how to mount three folder?
/odoo/enterprise
/odoo/custom_hrms/
/odoo/custom_accounting/

if I use -v three times, it raise an error. I will be thank full to anyone who let me tell the solution.

**Comment by anhvu-sg** [comment]
> 

hi @Tarikol-Islam , you have to mount three folders in the docker-compose.yml file (check my example [here](https://github.com/anhvu-sg/odoo-development-template/blob/16.0/docker-compose.yml#L29))

```
volumes:
      ...
      - path/to/enterprise:/mnt/enterprise
      - path/to/custom_hrms:/mnt/custom_hrms
      - path/to/custom_accounting:/mnt/custom_accounting
      ...
```

Then in the `odoo.conf` file, update addons_path

```
addons_path = /mnt/extra-addons,/mnt/enterprise,/mnt/custom_hrms,/mnt/custom_accounting
```

**Comment by Tarikol-Islam** [comment]
> > 
> 
> hi @Tarikol-Islam , you have to mount three folders in the docker-compose.yml file (check my example [here](https://github.com/anhvu-sg/odoo-development-template/blob/16.0/docker-compose.yml#L29))
> 
> ```
> volumes:
>       ...
>       - path/to/enterprise:/mnt/enterprise
>       - path/to/custom_hrms:/mnt/custom_hrms
>       - path/to/custom_accounting:/mnt/custom_accounting
>       ...
> ```
> 
> Then in the `odoo.conf` file, update addons_path
> 
> ```
> addons_path = /mnt/extra-addons,/mnt/enterprise,/mnt/custom_hrms,/mnt/custom_accounting
> ```

Thanks, 👍 but what if I don't use yml file ??
Is it possible to specify in docker run -v ?

**Comment by SmithJohn45** [comment]
hi all, i am struggling to create 3 different containers and follow this link to create one successfully, https://github.com/bithabib/docker_course
now I am searching for how to create another one which should be separate from already created including database part and I can work on all versions through their containers but don't know how to configure things including Pycharm community edition to achieve this? 
please help to work with different odoo versions separately thru different containers.
with regards to all seniors.
