### ISSUE TITLE
Docker installation / error using demo data

### ISSUE THREAD

**Issue by andrestone** [odoo/docker#237]
An exception happens when using docker recommended setup.

To reproduce:
1) ```$ docker run -d -e POSTGRES_USER=odoo -e POSTGRES_PASSWORD=odoo -e POSTGRES_DB=postgres --name db postgres:10```
2) ```$ docker run -p 8069:8069 --name odoo --link db:db -t odoo```
3) Install Expenses module in a new database with demo data
4) Click on a product inside the registered expense

![image](https://user-images.githubusercontent.com/7958086/51555448-e2693d00-1e77-11e9-9daf-5cefec39b5a8.png)

**Comment by d-fence** [comment]
I cannot reproduce. Can you confirm that you still encounter that issue ?
