### ISSUE TITLE
wkhtmltopdf error

### ISSUE THREAD

**Issue by pawa2007** [odoo/docker#238]
I get the following error when I try to generate a pdf report using the `Preview` functionality in Quotations in my cloud hosting provider instance. It works fine when I use it on my local machine.

`WARNING demo odoo.addons.base.models.ir_actions_report: wkhtmltopdf: b'Exit with code 1 due to network error: TimeoutError\n'`

**Comment by pawa2007** [comment]
Issue resolved by doing the following (thanks to the suggestion by Robin Chatfield [here](https://www.odoo.com/forum/help-1/question/how-to-change-the-value-of-web-base-url-to-get-the-correct-header-footer-css-82516)):

**Leave web.base.url as is and set report.url to http://0.0.0.0:8069**

**Comment by W360S** [comment]
it fixed my issue

**Comment by kinsoft-id** [comment]
Thanks.. it fixed my issue too

**Comment by shardulvashi** [comment]
I have added report.url to https://0.0.0.0 and it worked like charm. Thank you.

**Comment by adebuhr** [comment]
Hello, i added the report.url and the web.base.url to my Settings but i get the Error-Message in my Log.
The Report looks fine in the Web-Preview but is broken in the PDF. (e.g. missing images).

Does anyone have a solution for me?

Im using Odoo 15.

**Comment by mlopesbjj** [comment]
Perfect for Odoo 16.0.
I used report.url: http://0.0.0.0:8069

**Comment by jeffryjdelarosa** [comment]
> Issue resolved by doing the following (thanks to the suggestion by Robin Chatfield [here](https://www.odoo.com/forum/help-1/question/how-to-change-the-value-of-web-base-url-to-get-the-correct-header-footer-css-82516)):
> 
> **Leave web.base.url as is and set report.url to http://0.0.0.0:8069**

God Bless you

**Comment by Abrascha** [comment]
@pawa2007 Thank you very much. you saved my life. 
For odoo v17: activate developer mode first to display Technical options

**Comment by JoseRobertoMejiaPacheco** [comment]
Thanks
Reference
![Screenshot from 2024-12-05 10-00-26](https://github.com/user-attachments/assets/46ddd8e4-bd3c-41a0-8bb1-cdb81808cd61)

**Comment by ngthwi** [comment]
> Issue resolved by doing the following (thanks to the suggestion by Robin Chatfield [here](https://www.odoo.com/forum/help-1/question/how-to-change-the-value-of-web-base-url-to-get-the-correct-header-footer-css-82516)):
> 
> **Leave web.base.url as is and set report.url to http://0.0.0.0:8069**

Worked for me too.
Odoo 17 community edition

Thanks a lot

**Comment by alenas** [comment]
Worked for Odoo 18, as well, after upgrade from Odoo 14.
Document templates were not rendering without report.url set.

**Comment by mohan-13** [comment]
Worked for Odoo 16 as well just by setting report.url
