### ISSUE TITLE
[10.0] Creating image from Dockerfile

### ISSUE THREAD

**Issue by TristanMozos** [odoo/docker#247]
When I try to make an image with the Dockerfile, entrypoint.sh and odoo.conf of 10 version I take the next error:

Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/InRelease  Unable to find expected entry 'main/binary-amd64/Packages' in Release file (Wrong sources.list entry or malformed file)

E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by d-fence** [comment]
Sorry to say that Odoo 10 is not longer supported.
Seems to be a Debian problem.
