### ISSUE TITLE
Run multiple instances

### ISSUE THREAD

**Issue by risoul** [odoo/docker#25]
You say there it is possible to run multiple instances: https://github.com/odoo/docker-docs/tree/master/odoo#run-multiple-odoo-instances

I tried (my postgres name running is db-TEST) to launch another instance
docker run -d -p 127.0.0.1:8075:8069 --name odoo5 --link db-TEST -t odoo

8069 show odoo, works fine
8075 show blank page

What did I miss?

And what if I want one different psql container for each odoo instance?

**Comment by risoul** [comment]
I had to rundocker run -d -p 8075:8069 --name odoo5 --link db-TEST -t odoo
and it run at 0.0.0.0 like the first working instance.

But then i get 500 internal error

**Comment by md5** [comment]
The db link is expected to be called `db` inside the container. You might try `--link db-TEST:db` instead.

**Comment by md5** [comment]
From the docs:

> The alias of the container running Postgres must be db for Odoo to be able to connect to the Postgres server.

**Comment by risoul** [comment]
Solved
