### ISSUE TITLE
How to install python dependencies in odoo image docker

### ISSUE THREAD

**Issue by sarveshwaranj** [odoo/docker#257]

**Comment by Sirfanas** [comment]
Hi,
To install dependencies in your Odoo container's you have 2 method

Note: if you are using docker-compose juste replace all docker command by docker-compose

## First is to create a Dockerfile and build it:

Dockerfile
```
FROM odoo:12.0
# Of course, you can change the 12.0 by the version you want

# If you have to install from pip and using Odoo >= 11.0
RUN python3 -m pip install WHAT_YOU_NEED

# If you have to install from pip and using Odoo < 10.0
RUN python -m pip install WHAT_YOU_NEED

# If you need to install something with apt, if not working try to add apt-get update
# RUN apt-get update
RUN apt-get install PACKAGE_NAMES
```

Then just build your image and tag it as you want:
```
docker build . -t odoo_with_extra_dependencies:VERSION
```

With docker-compose:
```
services:
  ...
  odoo:
    image: odoo_with_extra_dependencies:VERSION
    build: .
  ...
```

Then use the previous tag to create / run container with your image

## Second method is to install into a running container

If for any reason you don't want to build a new image or need to install deps in an existing container

YOUR CONTAINER HAVE TO BE STARTED !

First get your container name (or id)
```
docker ps
```

Then run installation command:
```
# If you have to install from pip and using Odoo >= 11.0
docker exec -it --user=root CONTAINER_NAME_OR_ID python3 -m pip install WHAT_YOU_NEED

# If you have to install from pip and using Odoo < 10.0
docker exec -it --user=root CONTAINER_NAME_OR_ID python -m pip install WHAT_YOU_NEED

# If you need to install something with apt, if not working try to add apt-get update
# docker exec -it --user=root CONTAINER_NAME_OR_ID apt-get update
docker exec -it --user=root CONTAINER_NAME_OR_ID apt-get install PACKAGE_NAMES
```

Finally, restart your container
```
docker restart CONTAINER_NAME_OR_ID
```

**Comment by Moro-Code** [comment]
Seems like this is not working with the Odoo 13.0 image and installing dependencies must be done when the container is running

**Comment by Sirfanas** [comment]
@Moro-Code I can confirm this is working in 13.0
But you have to be careful, sometimes there's pip installation whose depends on system requirements, please try to install your deps with an apt install instead of a pip, so apt will retrieve system deps for you !

**Comment by Moro-Code** [comment]
@Sirfanas whoops, figured out why it wasn't working. I switched to the odoo user before running pip. So it would install in /var/lib/odoo/.local but would not persist

**Comment by Heki67** [comment]
![image](https://user-images.githubusercontent.com/43398131/87438158-62a9d200-c619-11ea-8546-2ab86a2dc32e.png)
![image](https://user-images.githubusercontent.com/43398131/87438184-6ccbd080-c619-11ea-8418-71e8471a2f53.png)
I have already switched to the odoo user but it still get some errors. Could you please help me out.

**Comment by Sirfanas** [comment]
> ![image](https://user-images.githubusercontent.com/43398131/87438158-62a9d200-c619-11ea-8546-2ab86a2dc32e.png)
> ![image](https://user-images.githubusercontent.com/43398131/87438184-6ccbd080-c619-11ea-8418-71e8471a2f53.png)
> I have already switched to the odoo user but it still get some errors. Could you please help me out.

Hi,

You should run as root user and not odoo to install anything
Then at the end of the Docker file go back to odoo user

**Comment by Heki67** [comment]
> > ![image](https://user-images.githubusercontent.com/43398131/87438158-62a9d200-c619-11ea-8546-2ab86a2dc32e.png)
> > ![image](https://user-images.githubusercontent.com/43398131/87438184-6ccbd080-c619-11ea-8418-71e8471a2f53.png)
> > I have already switched to the odoo user but it still get some errors. Could you please help me out.
> 
> Hi,
> 
> You should run as root user and not odoo to install anything
> Then at the end of the Docker file go back to odoo user

Oh it works :)) Tks a lot

**Comment by kmmelcher** [comment]
For anyone wondering what the final result is: 

![image](https://user-images.githubusercontent.com/20446656/212887241-bade2a10-0554-4c24-b85c-2c24686a51c8.png)

OBS: I'm using odoo 14 but it works for any version. I'm also having to copy my requirements file inside the container.
