### ISSUE TITLE
Env configuration

### ISSUE THREAD

**Issue by cgarnier** [odoo/docker#266]
Add a way to configure odoo with env variable.
It s more convenient then mount the odoo.conf.

**Comment by kovacs-andras** [comment]
hi! Odoo is pretty envy about it's config file. Especially when it's unable to write into it.
I just defined my variables in the entrypoint.sh and wrote them to odoo.conf from there.
I recommend for you the same.

**Comment by d-fence** [comment]
You can configure Odoo with command line parameters or the config file.
It's does not use a lot of env variables.
Closing as it's more an Odoo related issue than an Odoo Docker issue.
