### ISSUE TITLE
GeoIP not working?

### ISSUE THREAD

**Issue by docsmith90** [odoo/docker#268]
Is GeoIP supported in the docker container? 

I haven't managed to make it work yet, I believe that I will need to provide a file mapping to the geoip databas, but is that all that is required? are the required python modules installed?

Thanks

**Comment by kovacs-andras** [comment]
hey! As I see there is a misunderstanding in Odoo, so be careful!
The default value in Odoo is: /usr/share/GeoIP/GeoLite2-City.mmdb
But if you install the geoip-database package from repo, it still contains the old .dat format.
https://support.maxmind.com/geolite-legacy-discontinuation-notice/

So if this file is true: usr/lib/python3/dist-packages/odoo/tools/config.py
maybe you just need to download+extract this archive:
https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz
And put/map the db here: /usr/share/GeoIP/GeoLite2-City.mmdb

I have no idea about the python requirements, but if you grep around in the addons folder, you can find these:
crm_reveal/models/crm_reveal_rule.py:from odoo import api, fields, models, tools, _, **_geoip_resolver**
http_routing/geoipresolver.py:    import **GeoIP**    # Legacy
http_routing/geoipresolver.py:    import **geoip2**
http_routing/geoipresolver.py:    import **geoip2.database**
http_routing/models/ir_http.py:from ..geoipresolver import **GeoIPResolver**

I'm pretty sure you should install them by yourself if needed.

Tell me if you get somewhere!

**Comment by d-fence** [comment]
It seems that [we cannot distribute the database](https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/).
So, it's better to download it by yourself and use a docker volume to mount it in your instance.

**Comment by sinaisinai** [comment]
i have the same issue
