### ISSUE TITLE
[10.0] Odoo - I cannot print

### ISSUE THREAD

**Issue by vladbejenaru** [odoo/docker#269]
I moved my DB from a standard server to docker. Everything functions so far pretty good except printing.
By printing the loading splash screen (screen gets grayed out and a wheel spins in the middle) gets stuck and nothing happens.
As far as I could see the wkhtmltox in installed inside the docker but wkhtmltopdf not.
Same symptoms I have when trying to send documents per email, with my assumption that the app gets stuck at generating the pdf attachment.

Is there is something that I could try? Thanks!

**Comment by Sirfanas** [comment]
Hi,
Could you give us the command or docker-compose file you use to create your odoo and postgres database ?

Can you also give a look at the log to check if something pop in it ?

You can also try to create a system parameter with:
Key: report.url
Value: http://0.0.0.0:8069

Sometimes I have to create it otherwise report doesn't print or print without css etc...

**Comment by vladbejenaru** [comment]
sorry, now it seems to work.... I do not know what to say..... at the beginning it did not generate at all the pdf, afterwards it generated it in a blank template (nothing from my template customization was there and there was simple texts per lines like in notepad) but now it functions... could be a fault also on client side (browser, os) or connection speed to server.

otherwise the dockers were spin as per instructions without changes on a debian buster machine

Thanks a lot for the support

**Comment by vladbejenaru** [comment]
after a little bit of tinkering here and there I am coming back to share some experience: this might be related to this problem: https://www.odoo.com/forum/help-1/question/why-does-my-odoo-wait-for-more-than-2-minutes-after-clicking-on-pay-now-ecommerce-63715
it is unrelated to the odoo docker, but might help...

once again thanks guys!

**Comment by d-fence** [comment]
Solved

**Comment by victor4pro** [comment]
Finally I solved the problem in odoo 14.0 thank you!!!.
