### ISSUE TITLE
Unable to mount custom addon in Odoo 11

### ISSUE THREAD

**Issue by icewing02** [odoo/docker#270]
Hi,

I was trying out the docker version of 11 as I prefer it in doing development work. However, I am unable to load the custom addon.

As per the following files:
- `docker-compose.yml` > `./addons:/mnt/extra-addons`
- `odoo.conf` > `addons_path = /mnt/extra-addons`

Even the dockerfile contains:
`RUN mkdir -p /mnt/extra-addons \
        && chown -R odoo /mnt/extra-addons`
`VOLUME ["/var/lib/odoo", "/mnt/extra-addons"]`

Yet, the addon doesn't seem to be found in the apps even after I have placed them inside the addons directory. I tried downloading an app from [https://apps.odoo.com](https://apps.odoo.com) but even it doesn't seems to work. I have restarted (using both up and start) the docker, updated app list, yet I am unable to find the apps I was hoping to see.

I have checked out the directories it is checking for the mounted files but it seems to only load the following:
`['/var/lib/odoo/.local/share/Odoo/addons/11.0', '/usr/lib/python3/dist-packages/odoo/addons']`

Is there anything I am missing here?

Thanks a lot,
Jay

**Comment by Sirfanas** [comment]
Hi, are you on Linux, Windows or Mac ?
Your .addons directly contains module's folder ? They aren't in subfolder ?

**Comment by icewing02** [comment]
Linux (Ubuntu 18.04). Yes, it contains module directories.

**Comment by icewing02** [comment]
I have also checked the contents of the Odoo container. The `/mnt/extra-addons` does exist with the following custom addons found inside it but Odoo is not loading the custom addons, and yes, the custom addon is confirmed working.

**Comment by Sirfanas** [comment]
Well,
I didn't paid attention to your addons directory, seem your config is not used
Could you run odoo and give the entire log ?

**Comment by Sirfanas** [comment]
Also can you give entire docker-compose.yml ?

**Comment by icewing02** [comment]
It's basically the [Odoo 11 Docker](https://github.com/odoo/docker/tree/b5f088de13927177263d6cbc5ebf7d39de4dcfa7) and their recommended docker-compose with custom addons as specified in [dockerhub](https://docs.docker.com/samples/library/odoo/).

**Comment by Sirfanas** [comment]
Well,
Try to chmod 777 on addons folder and the config file 
(I know it's not safe but we'll be fixed if your compose is well configurated)

**Comment by kovacs-andras** [comment]
Hi!

Definitely nooo! Never ever chmod to 777.

> chown -R 101:101

your addons folder because this is the uid/gid for the user odoo inside the container.
Plus dont't forget the 

> odoo -u all --stop-after-init

to get your stuff recognized / pumped to the db.

**Comment by W360S** [comment]
Mount out your config file to your local disk following:
    volumes:
      - odoo-data:/var/lib/odoo
      - ./config:/etc/odoo #custom config file
      - ./addons:/mnt/extra-addons
      - ./themes:/mnt/themes
      - ./default:/mnt/addons
then add config file like this: 
[options]
addons_path = /mnt/themes,/mnt/extra-addons,/mnt/addons
data_dir = /var/lib/odoo
Noted: config file in config/odoo.conf you need to manual create it before running docker-compose up

**Comment by d-fence** [comment]
Thanks for the answers
