### ISSUE TITLE
Odoo 13 released?

### ISSUE THREAD

**Issue by codeagencybe** [odoo/docker#273]
Hello,

When is the Odoo 13 Docker version being released? 
The details show updated 2 days ago but inside the repo it says last update August...

![image](https://user-images.githubusercontent.com/7568546/66310947-a8f53680-e90d-11e9-94ac-b0ce871f995d.png)

![image](https://user-images.githubusercontent.com/7568546/66310958-adb9ea80-e90d-11e9-8ee7-f0ccb286bd96.png)

**Comment by IDCOLL** [comment]
I second this question. Can we please get a docker update for version 13.

**Comment by W360S** [comment]
Vote for v13 comming out soon

**Comment by andrewdhastings** [comment]
Saw that v13 docker file was created, but not pushed to docker hub, any timeline on when that will be done?

**Comment by d-fence** [comment]
I have a [few things](https://github.com/docker-library/official-images/pull/6750) to fix before it's available on the hub

**Comment by llacroix** [comment]
@andrewdhastings if you want to test odoo13 with docker you can check my fork, it has support for swarm and secrets. It's still a bit experimental as I fix issues almost every week and improve the entrypoint regularly. And if you have issues I'd be more than happy to fix them.

Everyday a nightly build is created from the nightly release but this may change to once a week later to prevent too many frequent updates.

**Comment by llacroix** [comment]
@d-fence just for your information. It doesn't seem like nightly builds are up to date. At least some code in the web module is still has code before a merge merged 21 days ago. I made an issue as I discovered odoo 13 nightly do not work with odoo-enterprise code in master today. 

https://github.com/odoo/odoo/issues/39150

**Comment by IDCOLL** [comment]
> I have a [few things](https://github.com/docker-library/official-images/pull/6750) to fix before it's available on the hub

How are we doing with this release?

**Comment by d-fence** [comment]
@IDCOLL you can follow the Odoo13 Docker hub PR here: https://github.com/docker-library/official-images/pull/6750
Working on the wait-for-it issue right now

**Comment by d-fence** [comment]
Odoo 13.0 landed  docker-library/official-images@1a3fef756ef41438110bec79ac2334e8e1964703)

**Comment by llacroix** [comment]
@d-fence Is this why official images aren't updated as often? You have to create a PR to this project and it has to be merged by them to get updates?

**Comment by d-fence** [comment]
@llacroix yep, it's a part of the answer. On the other hand, I'll try to update it more often.

**Comment by jinnko** [comment]
@d-fence - thanks for maintaining this!

I've hit a problem upgrading from the latest odoo:12 to odoo:13.  Raised the ticket on the main project (odoo/odoo#39381) as it seemed more relevant there, and thought it might be worth mentioning here too.  Happy to raise a new ticket in this repo if you think it's relevant.

**Comment by pedrobaeza** [comment]
@jinnko please don't spam threads. You have received your answer in the issue you have opened.
