### ISSUE TITLE
Chromium and websocket-client packages missing for js testing

### ISSUE THREAD

**Issue by qdelcourte** [odoo/docker#277]
**Tested on version 12**

I'm not able to run my js tests because packages are missing :
 * python _websocket-client_ package
 * _chromium-browser_ package 

**Step to reproduce:**

Run a test with js web_tour

**Displayed in logs:**

```
WARNING db odoo.addons.my_addon.tests.test_js.TestJS: websocket-client module is not installed
INFO db odoo.addons.my_addon.tests.test_js: skipped 'websocket-client module is not installed'
```
After I have installed _websocket-client_ in container:
`INFO db odoo.addons.my_addon.tests.test_js: skipped 'Chrome executable not found'`

**Comment by kovacs-andras** [comment]
> **Tested on version 12**
> 
> I'm not able to run my js tests because packages are missing :
> 
> * python _websocket-client_ package
> * _chromium-browser_ package
> 
> **Step to reproduce:**
> 
> Run a test with js web_tour
> 
> **Displayed in logs:**
> 
> ```
> WARNING db odoo.addons.my_addon.tests.test_js.TestJS: websocket-client module is not installed
> INFO db odoo.addons.my_addon.tests.test_js: skipped 'websocket-client module is not installed'
> ```
> 
> After I have installed _websocket-client_ in container:
> `INFO db odoo.addons.my_addon.tests.test_js: skipped 'Chrome executable not found'`

It says 'Chrome executable not found' because you haven't installed yet.

**Comment by d-fence** [comment]
I'm sorry to say that the Odoo Docker image is not really made for development.
We want to keep the image as small as possible, so we do not plan to put Chrome on the image.
I think that the best option is to use your own image, derived from the base Odoo image.
Then add, chrome, websocket-client ...

**Comment by kovacs-andras** [comment]
> We want to keep the image as small as possible, so we do not plan to put Chrome on the image.

In this case I think I will have some pull requests.
