### ISSUE TITLE
Odoo 8.0 2015-04-01 nightly version error

### ISSUE THREAD

**Issue by andre-oa** [odoo/docker#28]
The nightly version of 8.0 dated 2015-04-01 has a programming error when you:
1) Create a new database
2) Check "Load demonstration data"
3) Install accounting

**Comment by aab-odoo** [comment]
Hello,

I tried it with an updated version of Odoo (2015-10-08) and i couldn't reproduce it. It has probably been solved meanwhile.

I'll push the update soon.

Regards,
