### ISSUE TITLE
[12:0] modifying odoo.conf in confing volume couse that odoo don't start

### ISSUE THREAD

**Issue by marcinkuk** [odoo/docker#288]
Modifying odoo.conf in confing volume couse that odoo don't start.

Release: 20191106

How to recreate bug:
uncommenting ";limit_time_cpu = 60" in odoo.conf and restart service

**Comment by llacroix** [comment]
@marcinkuk I doubt this has anything to do with your problem. Odoo will use default values with the default config which is pretty empty.  If odoo doesn't start, it's probably not the reason why it doesn't start. You should provide a log of what's happening.

**Comment by d-fence** [comment]
Seems not related to Docker
