### ISSUE TITLE
Adding additional modules to container

### ISSUE THREAD

**Issue by jl2035** [odoo/docker#294]
Hi, 

I've added a pip requirement into my Dockerfile ("pip install requests-oauthlib") and the package installs correcrtly, but in runtime this module does not exist:

> ModuleNotFoundError: No module named 'requests_oauthlib'

Is this the wrong way of adding python libraries to containers?

My Dockerfile:

```
FROM odoo:13.0
USER root
RUN apt-get update && apt install -y net-tools nano wget telnet curl python-pip
RUN pip install requests-oauthlib
RUN pip install requests_oauthlib  
ADD customaddons /mnt/extra-addons/
ADD config /etc/odoo/
ADD odoo-web-data /var/lib/odoo
USER odoo

```

**Comment by jl2035** [comment]
I think I fixed it. Installing the following packages did the trick:
 
python3-oauth python3-oauth2client python3-oauthlib python3-requests-oauthlib

**Comment by d-fence** [comment]
Nice, it can be closed then.
