### ISSUE TITLE
Dev process with docker

### ISSUE THREAD

**Issue by risoul** [odoo/docker#30]
What is the best process to test and deploy, what tools do you use?

ie. I want to install a new module
- how to sync from docker prod?
- then I install module, test it
- how to deploy to prod?

**Comment by aab-odoo** [comment]
Hello,

The purpose of using Odoo within docker is mainly for testing, not deploying.

When you run your Odoo container, mount the folder where your custom addons are located at /mnt/extra-addons. 
When logged in, update module list in "Settings" App (requires technical features), then your custom addons should appear in "Local modules".

Regards,
