### ISSUE TITLE
pyOpenSSL library is not in linked

### ISSUE THREAD

**Issue by turbodavid** [odoo/docker#300]
Hi, I'm trying to install a module that needs the pyOpenSSL library. Odoo Enterprise 13.0 is my version. Is there a way to link this library to the dockers image??

Best Regards,

David Perez

**Comment by d-fence** [comment]
Hello, I'm sorry to say that you have to use a custom Dockerfile. You can use this one as a template like `FROM odoo:latest` ... 
We cannot customize the official Odoo Dockerfile for each specific use case.

**Comment by jzazo** [comment]
Hi @turbodavid. Did you overcome this problem? Would you mind sharing how you fixed it? Thanks.

**Comment by jzazo** [comment]
I think I figured it out. I write here how I solved it:

Create a `dockerfile` with the following:
```
FROM odoo:13
USER root
RUN apt-get update
RUN apt-get install -y python3-openssl
USER odoo
```
From the command line in the dockerfile location, build a new docker image with
`$ docker build --tag odoo:13b`

Run the new docker image:
`$ docker run -v /path/to/addons:/mnt/extra-addons -p 8069:8069 --name odoo --link db:db -t odoo:13b`

**Comment by turbodavid** [comment]
Javier, haven’t solved. I installed the regular version in order to work with the library. I will try this.

Thank you!!!

Best regards,

David Perez
