### ISSUE TITLE
odoo 12 with python 3.6

### ISSUE THREAD

**Issue by omwik** [odoo/docker#301]
how to use odoo 12 using python 3.6, because by default it uses python 3.5.3

**Comment by c1ayton** [comment]
Hello. Have you solved this problem.

**Comment by omwik** [comment]
not yet, can you help for this problem?

**Comment by c1ayton** [comment]
I installed python3.6.8 and odoo12 in my ubuntu container

**Comment by omwik** [comment]
it's in one container or two containers, please share your dockerfile

**Comment by c1ayton** [comment]
I didn't use docerfile. Is a dependency installed in a container

**Comment by omwik** [comment]
so, you use docker exec at odoo 12 and install python 3.6.8? have restarted the container?

**Comment by c1ayton** [comment]
I installed odoo12 with python3 at ubuntu16.04.Installation of python3.6 in odoo12, an error in the restart container is not resolved!

**Comment by omwik** [comment]
yes I also have the same problem, normal to restart container

**Comment by ryantran-novobi** [comment]
@d-fence could you might take a look at this? On Odoo.sh, python 3.6.9 is used, but for container, it's 3.5.3

**Comment by d-fence** [comment]
I'm sorry but I won't.
Our Odoo Docker image is always based on the Debian stable at the time of the Odoo release.
For 12.0 it was Debian Stretch which provides Python 3.5.3.
You can make you own Docker image by changing the `FROM debian:stretch-slim` to the distribution you want.
