### ISSUE TITLE
Odoo [12.0] 

### ISSUE THREAD

**Issue by valero1120** [odoo/docker#306]
Greetings, perform the installation of Odoo with the Docker image, everything works fine when generating a report I get the following error 

wkhtmltopdf: b'Exit with code 1 due to network error: ConnectionRefusedError \ n

**Comment by d-fence** [comment]
Cannot reproduce.
Can you give more information on your setup ?

**Comment by valero1120** [comment]
saludos, es una configuración personalizada, la tuve que cerrar puesto que agregue unos repositorios personalizados de localización y facturación electrónica, si lo desea puedo ayudar a que hagas el tuyo. gracias por comentar..
