### ISSUE TITLE
How to reload and introduce modules in docker

### ISSUE THREAD

**Issue by c1ayton** [odoo/docker#308]
I made changes to some modules.And added modules.I look forward to reloading the module.
When I killed pid 1 with kill -9 in docker, I failed to use /usr/bin/odoo-u module_name

**Comment by d-fence** [comment]
I think that you could use Docker directly.
For example, start your Odoo Docker instance like this:
` docker run --rm -v filestore:/var/lib/odoo -v /path/to/addons:/mnt/extra-addons -p 8069:8069 --name odoo --link db:db -t odoo`
Create your database ...
Now, let's say that you want to update the `my_module` module:
```
$ docker stop odoo
$ docker run --rm -v filestore:/var/lib/odoo -v /path/to/addons:/mnt/extra-addons -p 8069:8069 --name odoo --link db:db -t odoo -u my_module
```

**Comment by c1ayton** [comment]
> 我认为您可以直接使用Docker。
> 例如，像这样启动您的Odoo Docker实例：
> 
> ```
> $ docker run --rm -v filestore:/var/lib/odoo -v /path/to/addons:/mnt/extra-addons -p 8069:8069 --name odoo --link db:db -t odoo
> ```
> 
> 创建数据库...
> 现在，假设您要更新`my_module`模块：
> 
> ```
> $ docker stop odoo
> $ docker run --rm -v filestore:/var/lib/odoo -v /path/to/addons:/mnt/extra-addons -p 8069:8069 --name odoo --link db:db -t odoo -u my_module
> ```

Thank you.I have a question.How do I update odoo code in an existing docker container

**Comment by d-fence** [comment]
Hello. To update the Docker image, just run `docker pull`
Then, if you want to use the latest image with a container, you have to stop the container and start a new one with the new image.
You cannot really use this image to keep a **running** container up to date.

**Comment by c1ayton** [comment]
> Hello. To update the Docker image, just run `docker pull`
> Then, if you want to use the latest image with a container, you have to stop the container and start a new one with the new image.
> You cannot really use this image to keep a **running** container up to date.

The latest container. Odoo source code is not made some modifications
