### ISSUE TITLE
Addons mounted but not showing

### ISSUE THREAD

**Issue by risoul** [odoo/docker#31]
I want to add an addon.

I push the unzipped addon (website_product_rss) to /home on my host.
Then I chmod -755 -R it.
Then I start my container with -v /home:/mnt/extra-addons

I open a shell into the container and look at /mnt/extra-addons
Files are there with root and 755

Then I clic on update module list in odoo. The window close without error.
Going to local modules and search for rss
No module...

Tried to restart openerp-server from shell into container give

error: [Errno 98] Address already in use
^C2015-09-28 11:27:36,836 459 INFO ? openerp.service.server: Initiating shutdown
2015-09-28 11:27:36,836 459 INFO ? openerp.service.server: Hit CTRL-C again or send a second signal to force the shutdown.

Restarting the container works but no rss addon

Any help?

**Comment by risoul** [comment]
I ran container not from odoo image, but from an image I commited from initial odoo image.
Running container from odoo image mount correctly addons, and I can install.
Could you explain what is wrong when running my own image and not the original one?

**Comment by aab-odoo** [comment]
Hello,

I just tried it and it worked fine. I used odoo scaffolding to generate an addon skeletton, then run an Odoo container mounting the folder containing that addon into /mnt/extra-addons just like you did. I was then able to install it properly.

When logged in, don't forget to update module list (Left menu in the Settings App). This requires technical features.

Regards

**Comment by aab-odoo** [comment]
Note that you can't restart odoo from inside the container, Odoo being pid 1, when you kill it, it kills the container itself.

**Comment by sufyanel** [comment]
Risoul I'm facing the same issue in odoo 10. Did you get to solve this?

**Comment by thomas15v** [comment]
@sufyanel Did you update the modulelist?
Also I recommend using [docker-compose.yml](https://gist.github.com/thomas15v/faa7d71eff4807b2e68bbcebddf62906) to manage the containers and its mounts.

**Comment by sufyanel** [comment]
Thanks @thomas15v , I can't believe the custom addon path wasn't included in config file and I was over looking. It is working. 
However I recall trying altering a prebuilt module's manifest slightly and it seemed it wasn't reflecting either. And yes, I was updating the module list/upgrading.
