### ISSUE TITLE
Missing possibility to include own python imports

### ISSUE THREAD

**Issue by kinafu** [odoo/docker#312]
For custom oddo add-ons you sometimes need Python modules, which are not required by the official odoo apps.
Unfortunately there does not seem to be an ultra simple way to install them into the odoo docker image.

So I came up with the idea to create my own odoo image by extending the docker image as follows:
```
# $ cat Dockerfile
FROM odoo:13.0
RUN apt-get update
``` 
The `RUN` command fails: 
```
+ apt-get update
Reading package lists...
E: List directory /var/lib/apt/lists/partial is missing. - Acquire (13: Permission denied)
```

**Comment by d-fence** [comment]
The default user is odoo: https://github.com/odoo/docker/blob/master/13.0/Dockerfile#L83-L84

**Comment by rossigee** [comment]
FWIW, here's a chunk from my Dockerfile...

```
FROM odoo:12

# Switch to root to add python modules needed by third party plugins.
USER root
RUN apt-get update && apt-get install -y \
	python3-redis \
	python3-boto3 \
	python3-cachetools \
	fonts-thai-tlwg
RUN pip3 install cerberus
USER odoo
```
