### ISSUE TITLE
Can't call function from others extra-addons

### ISSUE THREAD

**Issue by HieuMinh67** [odoo/docker#315]
Hi everyone, I am new to docker odoo and here is my problem. I have 2 module in extra-addons from module A i import .py file from B module with this code `from extra-addons.module_B.py_file_in_B import class_from_B` but when run docker-compose up I got this `ModuleNotFoundError: No module named 'extra-addons' - - -`
Here is my docker-compose.yml

> version: '2'
> services:
>   web:
>     build: .
>     image: odoo:13.0
>     container_name: web
>     depends_on:
>       - db
>     ports:
>       - "8069:8069"
>     environment:
>       - USER=odoo
>       - PASSWORD=odoo
>       - ODOO_JWT_KEY=secret_key
>     volumes:
>       - odoo-web-data:/var/lib/odoo
>       - ./config:/etc/odoo
>       - ./custom_addons:/mnt/extra-addons
>     networks:
>       - app-network
>   db:
>     image: postgres:12
>     ports:
>       - "5430:5432"
>     environment:
>       - POSTGRES_DB=postgresql
>       - POSTGRES_PASSWORD=odoo
>       - POSTGRES_USER=odoo
>       - PGDATA=/var/lib/postgresql/data/pgdata
>     volumes:
>       - odoo-db-data:/var/lib/postgresql/data/pgdata
>     networks:
>       - app-network
> volumes:
>   odoo-web-data:
>     driver: local
>   odoo-db-data:
> networks:
>   app-network:
>     driver: bridge

Could someone please help me solve this problem? Thanks a lot

**Comment by Ricoamal** [comment]
Finding Odoo addons path and foler using winscp 

Hi am facing the same issue here. I cant locate odoo neither the addons folder.
i have used these two commands.
-------------------------------------------------------------------
docker run -d -e POSTGRES_USER=odoo -e POSTGRES_PASSWORD=odoo -e POSTGRES_DB=postgres --name mydb postgres

docker run -v odoo\addon:/mnt/extra-addons -p 8069:8069 --name myisntance --link mydb:db -t odoo

-------------------------------------------------------------------

am using winscp to see my files n folders.
