### ISSUE TITLE
Odoo9 ?

### ISSUE THREAD

**Issue by risoul** [odoo/docker#32]
Odoo 9 just released today, when could we have a docker image for this?
Official image must be updated too on docker hub.

**Comment by SamVerschueren** [comment]
:+1:

**Comment by tehXor** [comment]
+1
v8 docker image was/is really good. Please keep it up with future versions as well!

**Comment by morvans** [comment]
It seems pretty straightforward to add
https://github.com/odoo/docker/pull/35
