### ISSUE TITLE
Add Certbot to Odoo Docker running on PhotonOS

### ISSUE THREAD

**Issue by dayhox** [odoo/docker#321]
I have 3 Systemd .service files that automatically start sshd, postgres and odoo upon startup of my PhotonOS VM. This all works well. 
I'd like to add certbot to my site and just need a kick in the right direction.
Should I add it into my existing .service files or add an additional one?
TIA
d

**Comment by d-fence** [comment]
You need a reverse proxy to use https. See [documentation](https://www.odoo.com/documentation/14.0/setup/deploy.html#https)
