### ISSUE TITLE
what is the design idea behind hardcoding dbname='postgres' and choosing this name.

### ISSUE THREAD

**Issue by f1-outsourcing** [odoo/docker#333]
If you have coded this[1], why the hell are you not adding the database name? I am so curious what made you do this. Because it is really a weird design decision. And if you hardcode a dbname, why 'postgres'??? Why not eg odoo/crm/erp or so? Choosing the name postgres is sort of the worst name you can pick.

[1]
  arg_parser.add_argument('--db_host', required=True)
    arg_parser.add_argument('--db_port', required=True)
    arg_parser.add_argument('--db_user', required=True)
    arg_parser.add_argument('--db_password', required=True)
    arg_parser.add_argument('--timeout', type=int, default=5)

**Comment by sbouillon** [comment]
Lol —- please. stop. opening. issues. The docker repo is an inappropriate place to post these type of issues. You need to go to the main repo where Odoo is built and pray a dev will spend their time on these senseless questions.

**Comment by lathama** [comment]
@f1-outsourcing I found https://github.com/odoo/odoo/pull/12885 which might help you.

If it does feel free to close this issue in an effort to clean up issues.

**Comment by lathama** [comment]
@f1-outsourcing thanks for the update. In an effort to clean up the issue queue can you close this issue?

**Comment by f1-outsourcing** [comment]
Oh yes sure, I thought you would close it.
