### ISSUE TITLE
Set Timezone

### ISSUE THREAD

**Issue by Maoie86** [odoo/docker#348]
How do you set the timezone for the docker image? It is currently set to UTC.

**Comment by siddjellali** [comment]
add TZ variable 👍 

```
    environment:
      - TZ=Europe/Paris
```

**Comment by Maoie86** [comment]
thank you!

**Comment by janikvonrotz** [comment]
This has no effect inside the container!

**Comment by lathama** [comment]
@Maoie86 please close this issue if you have the solution you need.
