### ISSUE TITLE
Docker Logs - showing escape characters

### ISSUE THREAD

**Issue by oerp-odoo** [odoo/docker#355]
Does Odoo outputs some escape characters via docker, because when I run Odoo I see this:

```
Removing xproject_odoo_1 ... 
Removing xproject_db_1   ... 
[1A[2K
Removing xproject_db_1   ... [32mdone[0m
[1B[2A[2K
Removing xproject_odoo_1 ... [32mdone[0m
[2BRemoving network xproject_default
```
If I run Odoo normally (without docker), I dont see those characters in logs.

Is there a way to hide them?

P.S. currently not using any special options, just simply running default docker image.

**Comment by lathama** [comment]
@oerp-odoo so you are running something like `docker logs <containernamehere>` and getting that output? Can you share the version of Odoo? Does this happen with Odoo 17?

**Comment by oerp-odoo** [comment]
> @oerp-odoo so you are running something like `docker logs <containernamehere>` and getting that output? Can you share the version of Odoo? Does this happen with Odoo 17?

No longer remember what was the problem (might be issue with sublime editor as I run command via it). But now I don't have this issue. Though I am using custom docker image.

**Comment by lathama** [comment]
If it is not a problem, please close out the issue.
