### ISSUE TITLE
The `MAINTAINER` instruction is deprecated

### ISSUE THREAD

**Issue by os-ia** [odoo/docker#361]
The Docker documentation, more specifically the Dockerfile reference, mentions that the `MAINTAINER` instruction is deprecated, and that `LABEL` should be used. Source: https://docs.docker.com/engine/reference/builder/#maintainer-deprecated

On Oct 12, 2019 [this change](https://github.com/odoo/docker/commit/6ba07c93c397b64825c8d0ba0c46cd24c3155f42) was introduced, changing the correct `LABEL maintainer=""` to the deprecated one.

I would be happy to submit a PR to fix it, if necessary.

**Comment by d-fence** [comment]
Thanks, for the reporting but this issue was already [discussed](https://github.com/odoo/docker/pull/296#issuecomment-616740517) and as you can read, the Docker Library maintainers prefer to not use LABEL.
