### ISSUE TITLE
Preserve Dockerfile 11.0 and earlier

### ISSUE THREAD

**Issue by josehbez** [odoo/docker#366]
I suggest  preserve the Dockerfile for Odoo 11.0 and earlier, for future reference.

* Create a new dir and place there or 
* Create a tag before deleting it

**Comment by themreza** [comment]
This can probably help you: https://forums.docker.com/t/how-can-i-view-the-dockerfile-in-an-image/5687/3

**Comment by llacroix** [comment]
@josehbez if you need past image, you might want to have a look at my fork https://github.com/llacroix/odoo-docker 

Don't expect much support from this odoo repo, if there are issues with old versions I can fix the scripts to build old docker odoo versions.

**Comment by josehbez** [comment]
> @josehbez if you need past image, you might want to have a look at my fork https://github.com/llacroix/odoo-docker
> 
> Don't expect much support from this odoo repo, if there are issues with old versions I can fix the scripts to build old docker odoo versions.

@llacroix  Thank you for your backup.

**Comment by llacroix** [comment]
@josehbez It's a completely different project from odoo/docker it shares little with it now. It's not as limitting and if you want to use addons just mount them in `/addons` they'll get automatically loaded . It supports secrets and other things so checkout the readme

**Comment by lathama** [comment]
@josehbez can you close this issue if it is not needed or supply an update on the need?
