### ISSUE TITLE
Discrepancy in claimed software license between Docker README and repo LICENSE 

### ISSUE THREAD

**Issue by thehale** [odoo/docker#381]
The [DockerHub README](https://registry.hub.docker.com/_/odoo/#:~:text=agpl%20) claims that Odoo uses the AGPL license ...
![image](https://user-images.githubusercontent.com/47901316/127897125-a59a3d96-cbd1-44cf-a516-7a16754002f9.png)

... but the actual community repo's [LICENSE](https://github.com/odoo/odoo/blob/14.0/LICENSE) file claims LGPL.
![image](https://user-images.githubusercontent.com/47901316/127897331-7308165b-8a8c-4b10-a54b-1c3b91c759d4.png)

**Which license does Odoo actually use?**

**Comment by lathama** [comment]
It appears this was fixed as found at https://github.com/docker-library/docs/blob/master/odoo/content.md @thehale can you confirm and close?

**Comment by thehale** [comment]
Looks great! Thanks for the clarification :D
