### ISSUE TITLE
Add possibility to control python version

### ISSUE THREAD

**Issue by lem8r** [odoo/docker#386]
Odoo 14 image is based on Debian image which ships with Python 3.7.3.

That version of python has bug [bpo-37764](https://bugs.python.org/issue37764) which leads to 100% CPU usage in some cases.
It can be easily fixed by upgrading to Python 3.7.5 which is not possible to do when base image is `debian:buster-slim`.

I propose to use Python image which is also based on [buster-slim](https://github.com/docker-library/python/blob/master/3.7/buster/slim/Dockerfile) but allows to manipulate Python version by changing tags.

**Comment by lavrenkov-sketch** [comment]
@lem8r how you solve it?

**Comment by lem8r** [comment]
I switched to own images.
