### ISSUE TITLE
Updated docker image for Odoo 12

### ISSUE THREAD

**Issue by JoseRamonGarcia** [odoo/docker#398]
As I can see, Odoo 12 docker image is no longer updated.

Any help to get my Odoo 12 image updated? I'm enhacing some localization terms in v12, and need updates in the docker image.

Thanks!

**Comment by arabkhemar** [comment]
@JoseRamonGarcia you can use the v12 Dockerfile to build your own image with latest DEB from nightly.odoo.com

**Comment by JoseRamonGarcia** [comment]
@arabkhemar there is no more updates on nightly.odoo.com for the 12 version, too 😥

**Comment by arabkhemar** [comment]
Yep ! But you can grab the latest deb and update at least addons from git repo... this can be done by building the docker image and extra commands:
- Remove addons dir in /usr/lib/pythonX/dist-packages/odoo/addons
- Copy Addons from git to previous path.

**Comment by JoseRamonGarcia** [comment]
@arabkhemar Thank you! I will try this!
