### ISSUE TITLE
Odoo 15 fonts 

### ISSUE THREAD

**Issue by yousef-soliman** [odoo/docker#400]
Hello All,
I faced a problem that when I print a report that contains Arabic characters it shows as a black square.
![Screenshot from 2021-12-14 09-11-45](https://user-images.githubusercontent.com/10993059/145951274-240e36ee-0dae-4121-ba98-812e615b1532.png)
 I investigated this problem I found the fonts not installed 
 i checked the Arabic fonts in Odoo 15
 `fc-list :lang=ar`
``

 Arabic Reports works on Odoo 14, so I checked the Arabic fonts in Odoo 14 

 `fc-list :lang=ar`

 `/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf: DejaVu Sans Mono:style=Book
/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf: DejaVu Sans:style=Book
/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf: DejaVu Sans:style=Bold
/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf: DejaVu Sans Mono:style=Bold
`

i think we should install Arabic fonts in Odoo 15.

**Comment by avbasic** [comment]
عاش يا يوسف

**Comment by avbasic** [comment]
Hi ,
The problem still exists even with Arabic fonts exists !

The fonts of the  invoices html reports did not change to be the Arabic font 
so the wkhtmltopdf still generate the error shapes 

I think there is a step missing here

**Comment by yousef-soliman** [comment]
Hi @avbasic 
i solved my issue by installing this font `fonts-dejavu-core`

**Comment by d-fence** [comment]
Thanks for the reporting. It appears that this is a real bug in the packaging and probably occurs for other languages that needs a multilingual font package.

That's why I propose a fix in the packaging system that will fix the Docker image once merged.

The description of the problem was very helpful to track the issue to its roots. Thanks.
