### ISSUE TITLE
Docker run "crashed" after docker build:  <Database connection failure>

### ISSUE THREAD

**Issue by Lazatman** [odoo/docker#405]
1°) After clonning github repository and enter to the folder doo15: https://github.com/odoo/docker/tree/master/15.0
2°) enter to the folder and build the Dockerfile sucha as: $ docker build -t odoo_i15:latest .
3°) After build run the docker image: $docker run odoo_i15
I get: 
>>>Database connection failure: could not translate host name "db" to address: Name or service not known

**Comment by luna9722** [comment]
Hi, I'm facing the same problem, please tell me if you resolved it ?

**Comment by Lazatman** [comment]
Yes I reslove the problem by specified docker network... And specified db_host and db_password when launching Odoo container

**Comment by M-Shabbir0346** [comment]
> Yes I reslove the problem by specifying docker network... And specified db_host and db_password when launching Odoo container

what are the ommand?

**Comment by lathama** [comment]
@Lazatman Can you close this issue if no longer needed?
