### ISSUE TITLE
[9.0] Can't install two modules because of missing files

### ISSUE THREAD

**Issue by mel-microcom** [odoo/docker#41]
For some reasons, it seems that at least four files are missing in the DEB package (odoo_9.0.20151008_all.deb) from which the Dockerfile gets Odoo's files. I've checked the latest nightly as of 16-11-2015 and the files are missing as well...

The consequence of this is that these two modules can't be installed (there might be others...) because of these missing files:

-Recruitment Process
-Slides

Strangely, only .doc and .pdf files are missing:

<odoo installation folder>/addons/hr_recruitment/data/hr_recruitment_demo_jones_cv.pdf
<odoo installation folder>/addons/hr_recruitment/data/hr_recruitment_demo_williams_cv.doc
<odoo installation folder>/addons/website_slides/static/src/img/keynote.pdf
<odoo installation folder>/addons/website_slides/static/src/img/odoo-cms-comparision.pdf

Thanks!

**Comment by sle-odoo** [comment]
Hello,
i've just fixed the issue upstream with https://github.com/odoo/odoo/commit/7fcc79da21a8ae580ce6472e9e105012caf76e28

It'll be fixed in the docker image the next time we update it.

Regards

**Comment by mel-microcom** [comment]
Hi there,

Now that was fast, thanks!!!

Cheers mate!

**Comment by aab-odoo** [comment]
Hi,

The docker image has been updated: 3c6b6b584b3ce996851a3247a9e3399d68492305

Regards

**Comment by mel-microcom** [comment]
Thanks again!
