### ISSUE TITLE
WARNING flanker not found

### ISSUE THREAD

**Issue by jaredkipe** [odoo/docker#43]
I know this is just a warning, but it would be nice if flanker was installed

`WARNING ? openerp.addons.website_crm_score.models.sales_team: flanker not found, email validation disabled`

**Comment by jaredkipe** [comment]
While I'm at it how about `watchdog`?

`WARNING ? openerp.service.server: 'watchdog' module not installed. Code autoreload feature is disabled`

**Comment by Tim-Erwin** [comment]
+1 for watchdog

If you don't wanna include in order to keep the image small, you could provide a developer image based on the original.

**Comment by jaredkipe** [comment]
@Tim-Erwin You could try my automated build hibou/odoo:9.0
It is a fork of Odoo's docker but with newer python base and some other packages (python-watchdog is in there).
