### ISSUE TITLE
There is no docker image for  the ARM64 architecture

### ISSUE THREAD

**Issue by laozhou0731** [odoo/docker#434]
There is no docker image for the ARM64 architecture

**Comment by amh-mw** [comment]
Duplicate of #396, #349

**Comment by lathama** [comment]
@laozhou0731 please check https://registry.hub.docker.com/_/odoo/tags as I see an `linux/arm64/v8` ARCH

Please close this issue if this answers your question.

**Comment by laozhou0731** [comment]
Thanks
