### ISSUE TITLE
Problem with docker for odoo16 - it fetches an old version of the source code

### ISSUE THREAD

**Issue by dominiquekonsuntack** [odoo/docker#444]
To reproduce:
create a docker for odoo 16.
create a new database
install the invoicing app

check the model: account.bank.statement
in the latest source code, there is a field: problem_description
in the database created earlier, when checking for this field, it does not exist.

Why it matters:
- for odoo CE, not impact, but when trying to install odoo enterprise in a docker, it will fail. Because the enterprise modules need this field.

**Comment by amh-mw** [comment]
Maybe related to what you're describing: the April 12 release of odoo:16 is using a stale `odoo` package from March 29; the same as the prior release.

```
% docker pull odoo:16
16: Pulling from library/odoo
...
Digest: sha256:4111b36648969a6a43c9e17612ececed985ed8b5f2526eefab684f8ae6cc3415
Status: Downloaded newer image for odoo:16
docker.io/library/odoo:16

% docker run odoo:16 pip3 show odoo
Name: odoo
Version: 16.0.post20230329
Summary: Odoo Server
Home-page: https://www.odoo.com
Author: OpenERP S.A.
Author-email: info@odoo.com
License: LGPL-3
Location: /usr/lib/python3/dist-packages
Requires: 
Required-by: 

```
