### ISSUE TITLE
Odoo 15: missing 'Apps' & 'Settings' icons

### ISSUE THREAD

**Issue by Pexers** [odoo/docker#452]
For some reason the icons for the 'Apps' and 'Settings' modules don't appear when starting Odoo v15.0 without any other modules installed.

**This issue is only fixed once the user installs a random module.**

<img width="600" alt="Screenshot 2023-05-14 at 10 43 06" src="https://github.com/odoo/docker/assets/47757441/8bca45fe-9798-40f5-baf4-0ec2c3461012">

**Comment by akash1520** [comment]
How to reproduce?

**Comment by Pexers** [comment]
@akash1520 a few weeks later this problem stopped happening.
