### ISSUE TITLE
debian bookworm

### ISSUE THREAD

**Issue by devkral** [odoo/docker#457]
Debian bookworm was released. It would be nice to have a new image based on it.

**Comment by devkral** [comment]
Whenever I try to propose an improvement (e.g. basing on the python image) and look through the code, I learn more and have to abandon my idea because it is better solved.

Good engineering!

**Comment by samip5** [comment]
https://github.com/samipsolutions/containers/pkgs/container/odoo

Based on Bookworm.

**Comment by lathama** [comment]
@devkral is there any action needed on this or can you close it?
