### ISSUE TITLE
Live chat simply won't work - maybe it's me... maybe it's Odoo?

### ISSUE THREAD

**Issue by Majestic7979** [odoo/docker#461]
The bot appears in my site as normal. But it NEVER transfers to a live agent that has joined the channel. It's only myself. I am using the database so it should know I am live. But if I open a window it simply does not transfer to me even though I am clearly online. I asked a friend to try and all the bot does is "checking if the agent is available" then "sorry no agents are available".

This is obviously terrible since I keep getting queries about my products which I want to answer there and then, but it forces potential customers to leave their email for a response later. It's frustrating to customers to have a live chat that doesn't work. It's rather pointless! I have been to sites that offer live chat only to find that nobody is ever available and my personal impression is that it's pointless and unprofessional. So I had to remove the live chat altogether because I am far from unprofessional and unresponsive. I deliver amazing service to all my customers, even ones that didn't buy anything yet.

How can I get this thing to work? I am using traefik reverse proxy, I am capturing traffic on path /websocket and sending to port 8072 of my odoo instance. I max max cron = 1 and workers = 8. proxy_mode = true. All the other traffic that is not on /websocket is being sent to port 8069 which is the odoo port. The rest of the site works normally.
PS- I had to slightly amend the way the config is written because I don't have karma to post links according to the forum and it thinks the domains below are links... don't worry my traefik config is proxying as normal including the yaml indentation.
I run Odoo on docker. These ports are exposed in my CLI command: -p 8069:8069 -p 8072:8072

I also have this set on on my traefik:
## Odoo Storefront

http:
routers:

to-odoo-storefront-https:
entryPoints:
- "web-secure"
rule: "Host(`www. mystore.shop`) || Host(`mystore.shop`) && !Path(`/websocket`)"
service: odoo-storefront
middlewares:
- odooheaders
- odoosslheader
- gzip
tls:
certResolver: letsencrypt

to-odoo-storefront-http:
entryPoints:
- "web"
rule: "Host(`www. mystore.shop`) || Host(`mystore.shop`)"
middlewares:
- gzip
- httptohttps
service: odoo-storefront

# websocket to make live chat function - port 8072 internal in container
to-odoo-storefront-https-websocket:
entryPoints:
- "web-secure"
rule: "Host(`www. mystore.shop`) || Host(`mystore.shop`) && Path(`/websocket`)"
middlewares:
- odooheaders
- odoosslheader
- gzip
service: odoo-storefront-websocket
tls:
certResolver: letsencrypt

middlewares:

odooheaders:
headers:
customRequestHeaders:
Upgrade: websocket
Connection: upgrade
hostsproxyheaders: websocket,Upgrade
forceSTSHeader: true
sslRedirect: true

odoosslheader:
headers:
customrequestheaders:
X-Forwarded-Proto: https

gzip:
compress: true

httptohttps:
redirectScheme:
scheme: https
permanent: true

services:

odoo-storefront:
loadBalancer:
servers:
- url: "httpIPofserverZ:8069"
passHostHeader: true

odoo-storefront-websocket:
loadBalancer:
servers:
- url: "httpIPofserverZ:8072"
passHostHeader: true

What am I missing? While I really appreciate what Odoo has done for me so far, I think based on my internet searches that this Live Chat is not being maintained well because everyone seems to not be able to get it work.

From what I was reading when a customer opens a chat Odoo will automatically pass to the agent to has joined the channel. The chat will show anywhere in the database UI and also in the Discuss tab. But it never ever does! I noticed that the dot near my name is not green when I'm in the discuss tab. Sometimes it was but even then I would not get a live chat through to me.

**Comment by lathama** [comment]
@Majestic7979 can you confirm what version of Odoo this is and if you have tested with Odoo 17? You may want to look at https://github.com/odoo/odoo/issues?q=is%3Aissue+chat to see if there is any related issue.

**Comment by Majestic7979** [comment]
No it was my issue. I resolved by changing the Traefik rule from this:
rule: "Host(www. mystore.shop) || Host(mystore.shop) && Path(/websocket)"
to this:
rule: "Path(/websocket) && Host(www.mystore.shop) || Host(mystore.shop)"
