### ISSUE TITLE
Odoo

### ISSUE THREAD

**Issue by SaudMushtaq** [odoo/docker#465]

**Comment by lathama** [comment]
@d-fence can you close this issue please

**Comment by lathama** [comment]
@amigrave @assellalou @joda-odoo @Julien00859 @Louciole @odoostan @rco-odoo @sleepy-monax 

Who would be best to help manage this repo? Can someone with rights look at these issues/PRs as users do not close.

**Comment by Julien00859** [comment]
On top of my head I think of @vava-odoo who is doing some triage duty on the odoo/odoo repository, maybe he'll agree to watch over this repository too.

**Comment by vava-odoo** [comment]
@Julien00859 I'm only discovering this repo, so no I won't manage it. I already have a huge list of issues awaiting in odoo. Sorry

**Comment by Julien00859** [comment]
@lathama to answer your question

> Who would be best to help manage this repo?

Nobody. We simply do not watch over issues, we let users open them and answer each others. We don't have any triage policy going on so the kind of issues like this one are simply going to stay open, forever.

**Comment by amh-mw** [comment]
> Nobody. We simply do not watch over issues, we let users open them and answer each others. We don't have any triage policy going on so the kind of issues like this one are simply going to stay open, forever.

@Julien00859 Is there someone that we could notify for pull requests? Could we get some contribution guidelines here like https://github.com/odoo/odoo/blob/master/CONTRIBUTING.md

**Comment by lathama** [comment]
@Julien00859 Thanks, this helps.

**Comment by lathama** [comment]
For the Odoo team, a future task to consider for the teams would be to complete some of the items on https://github.com/odoo/docker/community for example. This can be extended to other repositories as well. Sadly this requires permissions on Github that I do not have or want at this stage. I miss the days of sending patch files in an email. :older_adult:

**Comment by lathama** [comment]
@odony In your spare time can you close this issue out. Thank you btw for cleaning up the others.
