### ISSUE TITLE
Odoo 17 image?

### ISSUE THREAD

**Issue by thomas15v** [odoo/docker#476]
Can an official odoo 17 image be provided?

I currently use this and haven't noticed any mayor issues. postgres-client and wkhtmltoppdf are provided from official repo's thought

**Comment by thomas15v** [comment]
I was a little bit to fast, wkhtmltopdf wasn't happy ... . Fixed it like this, but now I ain't happy:

```yml
FROM debian:bookworm-slim
MAINTAINER Odoo S.A. <info@odoo.com>

SHELL ["/bin/bash", "-xo", "pipefail", "-c"]

# Generate locale C.UTF-8 for postgres and general locale data
ENV LANG C.UTF-8

# Retrieve the target architecture to install the correct wkhtmltopdf package
ARG TARGETARCH

# Install some deps, lessc and less-plugin-clean-css, and wkhtmltopdf
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
        dirmngr \
        fonts-noto-cjk \
        gnupg \
        libssl-dev \
        node-less \
        npm \
        python3-num2words \
        python3-pdfminer \
        python3-pip \
        python3-phonenumbers \
        python3-pyldap \
        python3-qrcode \
        python3-renderpm \
        python3-setuptools \
        python3-slugify \
        python3-vobject \
        python3-watchdog \
        python3-xlrd \
        python3-xlwt \
        python3-geoip2 \
        python3-rjsmin \
        xz-utils \
        postgresql-client \
    && curl -o wkhtmltox.deb -sSL https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.buster_amd64.deb \
    && curl -o libssl1.1.deb -sSL ftp.us.debian.org/debian/pool/main/o/openssl/libssl1.1_1.1.1w-0+deb11u1_amd64.deb \
    && echo 'ea8277df4297afc507c61122f3c349af142f31e5 wkhtmltox.deb' | sha1sum -c - \
    && echo '975578b8e6cb8a0eb0734f34f3fa59e5507d9053 libssl1.1.deb' | sha1sum -c - \
    && apt-get install -y --no-install-recommends ./wkhtmltox.deb ./libssl1.1.deb \
    && rm -f /etc/apt/sources.list.d/pgdg.list \
    && rm -rf /var/lib/apt/lists/* ./wkhtmltox.deb ./libssl1.1.deb


# Install rtlcss (on Debian buster)
RUN npm install -g rtlcss

# Install Odoo
ENV ODOO_VERSION 17.0
ARG ODOO_RELEASE=latest
RUN curl -o odoo.deb -sSL http://nightly.odoo.com/${ODOO_VERSION}/nightly/deb/odoo_${ODOO_VERSION}.${ODOO_RELEASE}_all.deb \
    && apt-get update \
    && apt-get -y install --no-install-recommends ./odoo.deb \
    && rm -rf /var/lib/apt/lists/* odoo.deb

# Copy entrypoint script and Odoo configuration file
COPY ./entrypoint.sh /
COPY ./odoo.conf /etc/odoo/

# Set permissions and Mount /var/lib/odoo to allow restoring filestore and /mnt/extra-addons for users addons
RUN chown odoo /etc/odoo/odoo.conf \
    && mkdir -p /mnt/extra-addons \
    && chown -R odoo /mnt/extra-addons
VOLUME ["/var/lib/odoo", "/mnt/extra-addons"]

# Expose Odoo services
EXPOSE 8069 8071 8072

# Set the default config file
ENV ODOO_RC /etc/odoo/odoo.conf

COPY wait-for-psql.py /usr/local/bin/wait-for-psql.py

# Set default user when running the container
USER odoo

ENTRYPOINT ["/entrypoint.sh"]
CMD ["odoo"]
```

**Comment by Adridot** [comment]
Having the ARM version in docker is a huge step that we finally got, please go for version 17.0 now ! 
We are all waiting for it. 
@d-fence any news on the ETA ?

**Comment by llabusch93** [comment]
I am also in the waiting line...

**Comment by WaleedChayeb** [comment]
Looking forward the update to version 17...

**Comment by ibrohimislam** [comment]
I created a pull request for this, the wkhtmltopdf seems fine: https://github.com/odoo/docker/pull/478

**Comment by cj9255** [comment]
I'm surprised that it isn't listed alongside the community edition immediately after Odoo Experience.
Looking forward to the Docker release of 17 as well.

**Comment by looeee** [comment]
I'm also waiting for this so I can try Odoo 17.

**Comment by hertell** [comment]
There is a Bookworm-version out there. Wkhtmltopdf probably just did not update it on their downloads-page, because the project is more or less dead. You can find all their packages over here
https://github.com/wkhtmltopdf/packaging/releases

**Comment by GuikiPT** [comment]
> There is a Bookworm-version out there. Wkhtmltopdf probably just did not update it on their downloads-page, because the project is more or less dead. You can find all their packages over here https://github.com/wkhtmltopdf/packaging/releases

Well didn't know about that, will update it back to Bullseye when I had time.

**Comment by GuikiPT** [comment]
So I was checking now and the Odoo Docker Repo has now an Dockerfile of Odoo17.

So as officialy added by odoo, you should use it:
https://github.com/odoo/docker/tree/master/17.0

**Comment by haimai-sa** [comment]
Great

**Comment by GuikiPT** [comment]
@d-fence can you mark these as solved as you updated the repo that now contains an dockerfile of odoo17?

**Comment by hertell** [comment]
Why is Odoo 17 using an Ubuntu image?

**Comment by GuikiPT** [comment]
I don't know, but they followed my initial ideia.

**Comment by hertell** [comment]
It would have been better to stick to Debian, and not change it to something else!

**Comment by amh-mw** [comment]
In one of the OXP key notes, @fpodoo mentioned that they moved to Ubuntu to take advantage of LTS releases with five years of support.

**Comment by GuikiPT** [comment]
> It would have been better to stick to Debian, and not change it to something else! The continuity is suffering!

I'm personality changed from Debian to Ubuntu in my repo because I had some problems with Wkhtmltopdf.
When I tried to install it into Debian 12 I had some issues. Also the Wkhtmltopdf isn't supported into they main page but have some releases on GitHub for Debian 12.

Because that I changed to Ubuntu like I said before.
But for these repo, odoo changes from Debian to Ubuntu, don't know why.

Probably because that, or probably some dependency...

**Comment by GuikiPT** [comment]
> In one of the OXP key notes, @fpodoo mentioned that they moved to Ubuntu to take advantage of LTS releases with five years of support.

Oh ok that's nice

**Comment by hertell** [comment]
Well, the same 5 years goes also for Debian bookworm: https://www.debian.org/News/2023/20230610 Talking docker images; running a lts-versions of debian/ubuntu is not realistic. I wonder who would be upgrading their odoo docker images within the next years..
