### ISSUE TITLE
getting error 99 Cannot assign requested address in outgoing email server - Odoo 17.0 Community Edition

### ISSUE THREAD

**Issue by jartavia05** [odoo/docker#485]
Impacted versions:
 
 - 17.0
 
Steps to reproduce:
 
 1. Run Odoo docker 17.0 in debian 12 server with default nginx configuration.
 2. Create a new outgoing email server
 3. Set up a gmail account using username/password and/or OAuth Gmail (is happening in both)
 4. Click Test connection

Note: The exact same configuration is working in older odoo dockers. Already tested with odoo 12.
 
Current behavior:
 
 - Invalid operation - 99 Cannot assign requested address

![image](https://github.com/odoo/docker/assets/8932312/41c3560f-3ee2-4e2e-b750-fceae5fe48f6)

 
Expected behavior:
 
 - Test connection Successfully.

**Comment by lathama** [comment]
Can you share your docker command and or docker-compose.yml here?

**Comment by jartavia05** [comment]
I already resolved the issue. It was a port blocking in the cloud side. They open the port and magically everything works.
