### ISSUE TITLE
Apply docker compose

### ISSUE THREAD

**Issue by bigstones** [odoo/docker#492]
If there docker-compose.yml

It will make it easy to serve in any environment.

https://docs.docker.com/compose/

**Comment by amh-mw** [comment]
I'm not sure that there's a "one size fits all" docker-compose.yaml that would be useful for everyone, or in all situations. I have half a dozen myself for various development and testing scenarios, and to top it off, I don't actually use docker-compose to run Odoo in production!

That said, if you have any specific questions on setting up a docker-compose.yaml for Odoo, ask away!

**Comment by lathama** [comment]
@bigstones There are example docker-compose.yml mentioned at https://hub.docker.com/_/odoo which may answer your questions. If they do can you close this issue?

**Comment by lathama** [comment]
@bigstones did you find the example docker compose at dockerhub yet? If they answer your query can you kindly close this issue?

**Comment by bigstones** [comment]
@lathama Thank you for your response, I've checked the compose sample.
Sorry for the late reply Have a nice day!
