### ISSUE TITLE
Update Odoo release in the dockerfile to include commit 7e9a873

### ISSUE THREAD

**Issue by Joe-Pat** [odoo/docker#500]
The latest version of Enterprise addons - especially account_report - is looking for : 
`<xpath expr="//div[@id='bank_and_cash_container']" position="inside">`

This has been added in the commit 7e9a873 4 days ago (20240405) but is not available in the nightly of this day. Please update the docker image to the latest release.

Thank you

**Comment by amh-mw** [comment]
@Joe-Pat I recommend opening a partner support ticket instead and closing this issue; issues here are generally ignored. The historical release cadence for this repository outside of a major version rotation is biweekly, so I suspect you're ten days out from a new image.

**Comment by hertell** [comment]
Why are you not modifying the Dockerfile yourself to meet your own needs?

**Comment by lathama** [comment]
@Joe-Pat it has been a few weeks, is the change you needed in the released image now?

**Comment by Joe-Pat** [comment]
I haven't had time to check this. I would have modified the Dockerfile myself if I didn't have other priorities in the meantime. Anyway, I believe that, if it follows the normal release process, then the modifications must have been included. Therefore I'm closing this issue, thank you all.
