### ISSUE TITLE
Location of 

### ISSUE THREAD

**Issue by dtsoden** [odoo/docker#501]
documentation not working and my local fix below
https://hub.docker.com/_/odoo/

In the last example 
***BAD***
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

***REPLACE WITH***
   volumes:
      - odoo-db-data:/var/lib/pgsql/data

**Comment by amh-mw** [comment]
@dtsoden Could you open this as a pull request over at https://github.com/docker-library/docs/blob/master/odoo/content.md and close this issue?

**Comment by dtsoden** [comment]
Anyone interested in seeing the fix and other configurations visit:
https://github.com/dtsoden/odoo-docker-compose
