### ISSUE TITLE
[Feature Request] Could it be possible to add fail2ban to the docker image?

### ISSUE THREAD

**Issue by josopu** [odoo/docker#505]
I am trying to add fail2ban to the docker, but it would be amazing to have it included on the docker image.

**Comment by amh-mw** [comment]
Instead of installing an additional package that everyone who uses this image may not want, build a custom image with a Dockerfile like this?

```Dockerfile
FROM odoo:17
USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        fail2ban \
    && rm -rf /var/lib/apt/lists/*
USER odoo
```

**Comment by derfl0** [comment]
May i ask: what attacks are you trying to prevent here?

**Comment by josopu** [comment]
I just like to salve guard all my exposed services.

**Comment by derfl0** [comment]
> I just like to salve guard all my exposed services.

In the Odoo Docker image the only exposed service is Odoo itself. No other service, like for example SSH, is running. So no need to protect anything

**Comment by josopu** [comment]
I'd like to protect Odoo itself
