### ISSUE TITLE
fails compilation of less in some templates

### ISSUE THREAD

**Issue by nuelgoz** [odoo/docker#51]
In later debian (>jessie) and ubuntu (>14.04) you may need to add a symlink as npm packages call node but debian calls the binary nodejs
$ apt-get install -y npm
$ sudo ln -s /usr/bin/nodejs /usr/bin/node

docker image is doing this by starting the container ?.

fails compilation of less in some templates

**Comment by jaredkipe** [comment]
Would you mind trying https://hub.docker.com/r/hibou/odoo/ ? I have also found issues with the built in less, and get a newer one from NPM in this container.  (as well as other things like PG9.5 support ant workers>0)

**Comment by sle-odoo** [comment]
As we are using debian jessie, it looks like we are not affected by this bug. I remember stumbling over it tough. However, everything is working fine and if this was the root issue then you would not be able to render any template, which is not the case here.

Regards
