### ISSUE TITLE
[Odoo 18.0 Docker Container] How to update to 16.0 - 18.0?

### ISSUE THREAD

**Issue by schwahue** [odoo/docker#521]
Hi guys, is there anyway for us to update this and subsequently the Odoo dockerhub repo to include Odoo 18.0?

Thanks

**Comment by LuvForAirplanes** [comment]
@schwahue Maybe you could update your ticket to say something like Odoo 18 Docker Container or something... that would be more clear.
I second this, I am an Enterprise customer, ready to buy more licenses, but we are waiting on Docker containers.

**Comment by schwahue** [comment]
It is updated to 18.0 :)
