### ISSUE TITLE
Odoo 18 - docker release

### ISSUE THREAD

**Issue by cmeldas** [odoo/docker#522]
When can we expect a release of the Odoo 18 as a docker image?
Thanks

**Comment by GordoPepper** [comment]
Oh yes please a release for Odoo18

**Comment by LuvForAirplanes** [comment]
Waiting to deploy an Enterprise system as soon as an image is available.

**Comment by jackadam1981** [comment]
Waiting to deploy an Enterprise system as soon as an image is available.

**Comment by daibaron** [comment]
Can you update the docker hub page to launch the container
