### ISSUE TITLE
[9.0] Database backup error

### ISSUE THREAD

**Issue by medined** [odoo/docker#59]
I set a master password, then tried to backup. At this stage, I have not installed any modules.

{noformat}
Database backup error: Postgres subprocess ('/usr/bin/pg_dump', '--no-owner', '--file=/tmp/tmpsoXqxu/dump.sql', u'department13') error 1
{noformat}

Odoo was started by these commands:

{noformat}
docker volume create --name d13-odoo
docker run -d -v d13-odoo:/var/lib/postgresql/data/pgdata -e PGDATA=/var/lib/postgresql/data/pgdata -e POSTGRES_USER=odoo -e POSTGRES_PASSWORD=odoo --name db postgres:9.5.3
docker run -d -p 8069:8069 --name odoo --link db:db -t odoo:9
{noformat}

**Comment by odony** [comment]
See #49, this seems to be a duplicate

**Comment by odony** [comment]
tl;dr: fix your postgres docker command to force `postgres:9.4` instead of 9.5.3. If you strictly want PG 9.5 you'll need to change the Odoo 9 docker image, see https://github.com/odoo/docker/issues/49#issuecomment-224269313

**Comment by sylnsr** [comment]
All you need to do is create your own image with the correct version of the client tools. For example, I am using PG 9.6 and solved it by simply adding this to my base image: https://github.com/idazco/odoo-docker-ez/blob/master/10/Dockerfile#L83
