### ISSUE TITLE
odoo localhost connection refuse

### ISSUE THREAD

**Issue by Fitmavincent** [odoo/docker#63]
I followed the tag notes step by step and successfully run on localhost 8069 port, however, it stopped suddenly after I entered the odoo UI and giving me error : dial unix ... connection refused...

**Comment by jaredkipe** [comment]
You mean you got through the Odoo database initialization screen, but after than nothing happened?

Anything out of the postgres or odoo docker logs?

**Comment by sle-odoo** [comment]
Closing as i cannot really reproduce, however i'm facing this issue randomly in osx but it's likely that it's due to docker-for-mac, which is, according to their github issues, not completely stable.

**Comment by Danisetiorini** [comment]
:)
