### ISSUE TITLE
Failed to query Docker registry

### ISSUE THREAD

**Issue by 62ML** [odoo/docker#67]
Hi,
I'm using docker from a NAS/Synology. It's working fine except for your ODOO products ... the server NAS/Docker return a "failed to query registry".
What's wrong ... probably not the synology, the Docker repository seems to be ok ... 
Could you help ?
Alternatively, I can add an image from an URL or a File. Could you provide these links for ODOO 9  ?
Thank you,
M

**Comment by jaredkipe** [comment]
I think you need to look deeper on your side. Can you pull random images from hub.docker.com?
Odoo does not control that infrastructure.

**Comment by 62ML** [comment]
I'm just closed a support ticket with Synology. According to Synology, nothing abnormal on their side and nothing abnormal in logs ....
Yes, I can you pull other images .... without problem !
Thank you for your help ! Do you have another registry to test ...

**Comment by jaredkipe** [comment]
But you have to understand that there isn't something special about odoo compared to the others, assuming that they are from hub.docker.com.

Can you give an exact `docker run` or `docker pull` command that you run that gives this error?

**Comment by solarisx** [comment]
Hi, I have the same problem. Other container work well on the Synology NAS with docker 1.112-0268.
Did you found a solution?

**Comment by 62ML** [comment]
Hi, No ... only a strange workaround : 1) On Ubuntu Execute a Docker Pull 2) On Synology Add Image from a file. The second operation is probably going to fail ... but the image is there and the container is working ! Synology is unable to explain.

**Comment by solarisx** [comment]
Tried another odoo: https://hub.docker.com/r/xcgd/odoo/. This works, but NAS wizard does not show dialog for version selection.

**Comment by 62ML** [comment]
Hi, if you provide your email, I can try to reply with the "docker pull" file of ODOO lastest ....

**Comment by solarisx** [comment]
Ok, thanks. Hope it gets fixed in near time.

**Comment by solarisx** [comment]
Thanks, but i will try your solution first. Or maybe it gets fixed in some days.

**Comment by 62ML** [comment]
Ok, keep me posted !
In the meantime, I can confirm that the container is working despite de error message during the import !

**Comment by gustavogoette** [comment]
Hi there. Any news about this?  Same error trying to use https://hub.docker.com/_/odoo/ on synology 👍 
"failed to query registry"

**Comment by lethunder** [comment]
Hello,
you need to get to registry parameters and make sure you are on "docker hub"

**Comment by matraz17** [comment]
Hmzz, getting same error... can't pull the Odoo to Synology Docker, anyone a solution?

**Comment by maxzaikin** [comment]
Hi All, i have the same issue. I'm freaking tired with the Synology stupidity!!! I'm think ti switch on different NAS...

**Comment by eabrega** [comment]
Hi all

I'm unable to search for new docker. I'm always receiving the error message "Failed to query registry". This has been working in the past, since i have two docker containers running. I'm using the default Docker Registry Setting from Synology -> Docker Hub (https://registry.hub.docker.com)

**Comment by Canule** [comment]
> Hi Customer,
> 
> Thank you for contacting Synology support.
> 
> If the error is coming from the Odoo container, it's likely you'll need to check the settings on Odoo side to make sure they're correct.
> There should be a pop-out for the container which will bring up the developer help page.
> 
> I would also start with some help and guidance on the forums from other power users:
> https://forum.synology.com/enu/viewtopic.php?f=184&t=144905&p=539305&hilit=odoo#p539305
> 
> If you have any further questions, please feel free to contact Synology Support Team again.
> 
> —
> Best regards,
> 
> A W.
> Technical Support Engineer
> Synology Inc.

**Comment by FittEyes** [comment]
The suite includes various Odoo applications such as Sales Purchase Management, Accounting and Warehouse Management. As a leading implementing [partner for Odoo](https://www.techloyce.com/odoo-partner/), we ensure that our expert experts are responsible for the implementation. The organization's long-term goals cannot be met without allowing for mistakes. For companies focusing on retaining their valued clients, it is one of the cheaper solutions.
