### ISSUE TITLE
PDF Invoice Footer Missing

### ISSUE THREAD

**Issue by ebotech** [odoo/docker#7]
First off thanks for your excellent work on odoo and this docker.

When generating a PDF invoice in the accounting module the header and content print fine but there isn't  any footer.

Tested with released docker instances run using:
docker run -d -e POSTGRES_USER=odoo -e POSTGRES_PASSWORD=odoo --name db postgres
docker run -p 127.0.0.1:8069:8069 --name odoo --link db:db -t odoo

With a fresh db with the demo data in and the accounting module installed.

**Comment by aab-odoo** [comment]
Hello,

This is a known issue with the recent releases (0.12.2 and 0.12.2.1) of wkhtmltopdf (see https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2183).

Odoo works fine with the previous version (0.12.1) of wkhtmltopdf, but this version is not available on Debian Jessie (on which our image is based, for other reasons).

We currently have multiple open issues on the wkhtmltopdf repository and we hope to fix this very soon.

Regards.

**Comment by aab-odoo** [comment]
This is fixed by rev. 43973dfcf98c787f04fe0e2b3b41782c96daea00.

Thanks @sle-odoo

**Comment by odony** [comment]
For the record, a "more permanent" workaround had to be implemented even for 0.12.1, as the loading of external JS files seems to be semi-reliable (see wkhtmltopdf/wkhtmltopdf#2083)
The fix is at odoo/odoo@3c61ee5c68e3796bb29d2521123f2a867c9cc157, so we can now use 0.12.2.1 again.
