### ISSUE TITLE
[10.0] Can't connect to DB

### ISSUE THREAD

**Issue by larsmagnusherland** [odoo/docker#82]
By using **image: odoo:9.0** this docker-compose works without issues. Changing it to **image: odoo:10.0** , then all 4 containers start but all I get is "HTTP 500 Internal Server error" and the logs state that I cannot connect to the database. I do not use any custom configuration file, just the default one that comes when pulling the image down. I have tried to run all on the same host, separate hosts etc.. does not matter. It does not work when you have several containers.

Attached is the docker-compose.yml
[docker-compose.txt](https://github.com/odoo/docker/files/573592/docker-compose.txt)

The environment variable POSTGRES_DB: postgres is set due to the following logged at the Postgres:
FATAL:  no pg_hba.conf entry for host "xx.xx.xx.xx", user "odoo", database "postgres", SSL off

But doesn't seem to really matter if that line is present or not, still show exact same error in the logs.

If I connect to the postgre and do the following:
CREATE USER odoo WITH PASSWORD 'odoo';
GRANT ALL PRIVILEGES ON DATABASE postgres to odoo;

Creating the user manually and giving access to the database postgres, doesn't change the end result. Same error message in the logs.

Have tried to using the following postgre versions:
- 9.3
- 9.4
- 9.5
- 9.6

But all of them show exactly the same issue.

So something does not work correctly with the **image: odoo:10.0** that worked in earlier versions.

**Comment by sle-odoo** [comment]
Hello,

Sorry for any inconvenience caused.

You used the PG* environment variables to set your postgres credentials. This technique is not correctly working ([see this](https://github.com/odoo/docker/pull/74#issuecomment-256956274)), so we removed their use in a3d207f2d49c3a0eb0e959fbf2cb33909c382a3f and i renamed every PGx variable by x, to make it clear that they're not exported and not the ones used by postgres.

The quick fix for your docker-compose file is to replace in your odoo category
```
    PGHOST: db
    PGDATABASE: odoo
    PGUSER: odoo
    PGPASSWORD: odoo
```
by
```
    HOST: db
    PGDATABASE: odoo
    USER: odoo
    PASSWORD: odoo
```

The thing is, when i removed the use of the PG* environment variables, i took care of being backward compatible with the commands used in the documentation, and we only document the Docker Linking way in our current documentation.

While i agree that this was unexpected, we will soon refresh the documentation with docker-compose examples that will be officialy supported so i don't want to "fix" this issue. The use of PG* by Odoo was not really documented or supported so let's wait Odoo 11 to rely on them.

Regards
