### ISSUE TITLE
[9.0] No auto restart on mounted folder

### ISSUE THREAD

**Issue by PieterPaulussen** [odoo/docker#84]
I'm new to the docker story and I'm trying to integrate my Odoo development with a docker. 
The expected behaviour I want to achieve is: 
1. I run an Odoo docker image and configure the mounted folder to include my addons.
`docker run -v /my/local/folder:/mnt/extra-addons -p 8069:8069 --name odoo --link db:db -t odoo:9.0`
2. When I make changes and update the module in the mounted folder, the docker should automatically restart the image and update the module. There is no further need to update the module using the web interface.

I have already configured this setup for an Odoo V8 and the docker behaves as I expect.
However: When I want to do the same with and Odoo V9. The mounted folder does contain the changes I made to the addon folder. However the docker image does not auto restart on detecting the change (I think it doesn't even detect anything). After that I need to go to the web interface and update , etc. ...

I have not yet tried this on V10. I did not find any significant changes to the Dockerfile in V9 compared to V8. 

Any advice on how to achieve the expected behaviour or is there a bug?

**Comment by Yenthe666** [comment]
@sle-odoo can you give an official statement on this? 😉

**Comment by sle-odoo** [comment]
it's probably linked to some changes in Odoo itself.
i'll have a look today

**Comment by PieterPaulussen** [comment]
@sle-odoo Do you have any feedback on this issue? Thx!

**Comment by Yenthe666** [comment]
@sle-odoo any update on this one? (sorry for pinging you again)

**Comment by sle-odoo** [comment]
Hello,

Sorry for the delay. The `auto-reload` flag that [we set in the configuration file](https://github.com/odoo/docker/blob/master/8.0/openerp-server.conf#L4) is not implemented in odoo 9 and 10. This feature has been merged in another CLI argument: `dev`. It seems that the `dev` key is not usable in the config file though.

the idea would be to start your server with 
```
docker run -p 8069:8069 --name odoo --link db:db -t odoo:[9.0|10.0] -- --dev=reload
```

But when you start that, there's a warning:
```
2016-11-25 14:18:48,510 192 WARNING ? odoo.service.server: 'watchdog' module not installed. Code autoreload feature is disabled
```
 
Se we should replace [python-pyinofity](https://github.com/odoo/docker/blob/master/9.0/Dockerfile#L13) by [python-watchdog](https://pypi.python.org/pypi/watchdog) in the docker files 9 and 10.

I'll make a branch for that. In the meantime, you could just `docker exec -u root -it odoo /bin/bash` and type `apt-get install python-watchdog`.  Then you'll see in your logs:
```
2016-11-25 14:22:55,395 321 INFO ? odoo.service.server: AutoReload watcher running
```

Thanks for the report.

**Comment by PieterPaulussen** [comment]
@sle-odoo Hey! Thanks for your reply, greatly appreciated.
Will test this asap!

**Comment by PieterPaulussen** [comment]
@sle-odoo Tried to create a new docker image by using the code from the branch you made. Build succeeds however when I run the command `docker run -p 8069:8069 --name odoo --link db:db -t odoo:9.0 -- --dev=reload` I get the following response:
`Usage: openerp-server [options]`
`openerp-server: error: --dev option does not take a value`

**Comment by sle-odoo** [comment]
@PieterPaulussen Hi, so it seems that in v9 you do not have much granularity over the developer options you want to activate. It's just `--dev` that will add the reload feature among other things. You can also work with `--debug`. In v10, `--dev` accepts arguments to specify what you want to enable (auto reload, debugger in qweb, python debugger in the webclient,...)

If it's working for you i'll merge the branch.

Regards

**Comment by PieterPaulussen** [comment]
Hi @sle-odoo I tried running it with the code in the new branch. This is the output:
`pieterpaulussen@Pieters-MacBook-Pro:~/Downloads/docker-master/9.0$ docker run -v /Users/pieterpaulussen/OdooV9/odoo-van-roey/Encopro/:/mnt/extra-addons -p 8069:8069 --name odoo --link db:db -t testtesttest -- --dev`
`2016-11-28 20:26:27,055 1 INFO ? openerp: OpenERP version 9.0c-20161123`
`2016-11-28 20:26:27,056 1 INFO ? openerp: addons paths: ['/var/lib/odoo/addons/9.0', u'/mnt/extra-addons', u'/usr/lib/python2.7/dist-packages/openerp/addons']`
`2016-11-28 20:26:27,056 1 INFO ? openerp: database: odoo@172.17.0.2:5432`
`2016-11-28 20:26:27,346 1 INFO ? openerp.service.server: Watching addons folder /var/lib/odoo/addons/9.0`
`2016-11-28 20:26:27,347 1 INFO ? openerp.service.server: Watching addons folder /mnt/extra-addons`
`2016-11-28 20:26:27,620 1 INFO ? openerp.service.server: Watching addons folder /usr/lib/python2.7/dist-packages/openerp/addons`
`2016-11-28 20:26:28,000 1 INFO ? openerp.service.server: AutoReload watcher running`
`2016-11-28 20:26:28,017 1 INFO ? openerp.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069`
`2016-11-28 20:26:41,079 1 INFO ? openerp.addons.bus.models.bus: Bus.loop listen imbus on db postgres`
`2016-11-28 20:26:41,987 1 INFO ? openerp.addons.report.models.report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf`
`2016-11-28 20:26:42,446 1 INFO ? openerp.http: HTTP Configuring static files`
`2016-11-28 20:26:42,458 1 INFO ? openerp.http: Generating nondb routing`
`...`

So as you can see... The Autoreload is running. However when I change one of the files, XML or Python, the autoreload does not start.
Am I still doing something wrong? 

Steps I already used to try:
1. Copy code for 9.0 branch to each individual file. 
2. Checked that python-watchdog is installed on the docker. 
3. Rebuild everything from scratch..

Is there still something I'm missing? I wonder if it has something to do with running the code on OSX perhaps? (Though I doubt it.)

**Comment by sle-odoo** [comment]
@PieterPaulussen i know that there are some issues with editor that do not do atomic save. What's the one you're using? Beware that we only watch for modification, not creation/deletion. Also, a new record in an xml file won't be loaded.

**Comment by PieterPaulussen** [comment]
@sle-odoo I'm using Jetbrains Pycharm to edit my files. What I did to trigger the reload is remove a field from the view. I also edited a python file in a custom module.
When starting the docker, should I tell the watchdog which files it should monitor? I know I used the correct command (-v) to link my custom addons folder to the installation and that it's present in the Odoo config file.
I'm also testing a regular Odoo (source code install) and then I tried the --dev option. Unfortunately this does not trigger the correct response either. Could there be a link?

**Comment by sle-odoo** [comment]
Well one thing would be to make it work on a source install. It is at my end. Start odoo 9 with --dev, check that watchdog is installed and watching the right folders, edit a python file (i add a pass somewhere). Save (with vim in my case) and the watchdog should reload the server. It is working for me.

Now, with docker and osx:
I mount /tmp as extra-addons. If i edit the file from the host (osx) then the server doesn't reload. If a edit it from inside the docker, then the server reloads. If it's working with docker on linux i'll have to say it's a bug in docker on osx...

**Comment by PieterPaulussen** [comment]
@sle-odoo Yes, I believe that it must be a bug somewhere in docker for OSX. I wonder if I can report it somewhere. 
I will try to test it in a linux VM soon and provide feedback.

**Comment by sle-odoo** [comment]
there seems to be quite a lot of issues regarding the watch of files/directoies in their github https://github.com/docker/for-mac/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20watch.

I'll wait for your feedback to close this issue as we cannot do anything here to fix it (if it's that)

**Comment by PieterPaulussen** [comment]
@sle-odoo Ok, I still seem to have some troubles. What I already tried:
1. Install a clean Ubuntu 16.04 VM in virtualbox
2. Install docker
3. Clone the new Odoo Docker branch.
4. Build the new odoo image
5.a) start Odoo with the following command:
  `sudo docker run -v /home/pieterpaulussen/odoo-van-roey/Encopro:/mnt/extra-addons -p 8069:8069 --name odoo --link db:db -t odoo-test-reload -- --dev -u my_module`
I checked that the autoreload is running, but changing, adding or removing some code does not trigger a reload.
5.b) start Odoo with the following command: 
  `sudo docker run -v /home/pieterpaulussen/odoo-van-roey/Encopro:/mnt/extra-addons -p 8069:8069 --name odoo --link db:db -t odoo-test-reload -- --dev`
Did not work either. 
I still get the feeling there's something wrong with my installation. Do you pass any special command when building with the Dockerfile?

Thx for your feedback!
