### ISSUE TITLE
docker-compose.yml

### ISSUE THREAD

**Issue by hnaparst** [odoo/docker#87]
It would be great to have a working docker-compose.yml
The one in the comments does not work.

**Comment by sle-odoo** [comment]
we're working on that in https://github.com/docker-library/docs/pull/720

**Comment by hnaparst** [comment]
If possible, it should be able to handle several Odoo installations, all sharing the same Postgres server, although probably with different databases.

**Comment by sle-odoo** [comment]
@hnaparst i understand but it's more a matter of Odoo configuration than Docker configuration. Some comments on the `--db-filter` are present in the [deployment guide](https://www.odoo.com/documentation/9.0/setup/deploy.html).

If you want to contribute to the documentation feel free to do so.
see https://github.com/docker-library/docs/pull/752

**Comment by hnaparst** [comment]
Contributing to the documentation is a good idea, and I would love to do that.  But first, I would have to know how to use the software, and I would have to know the answers to these questions I am asking.  Otherwise, it would be like the blind leading the blind.

Regarding your link to the deployment documentation, yes, I have already read that.  My point is that I do not feel that this description really gives a user an actionable course forwards, and that several examples, including the use of a compose file, would be helpful.

**Comment by sle-odoo** [comment]
@hnaparst we can't use just a compose file here as we would need to send arguments to the odoo entry point. We could share a directory with two odoo configuration file, one with the key "dbfilter = db1" and the other one with the key "dbfilter = db2". create these two databases with one instance or another, then the Odoo instances will only see db1 or db2 on the postgres container. It'll do the trick.

I'm closing this issue as some docker compose examples are now on the [docker hub page](https://hub.docker.com/_/odoo/).
