### ISSUE TITLE
Two instances sharing the same postgres container

### ISSUE THREAD

**Issue by hnaparst** [odoo/docker#88]
I am trying to get multiple Odoo instances to use the same Postgres container following the instructions given in the official docker image for Odoo.   

When I open the second Odoo instance, I get a corrupted version of the start page of the first Odoo instance.

It should be possible to use the same Postgres container by merely specifying a different database for the second instance of Odoo.  However, I cannot see how to do that.

**Comment by sle-odoo** [comment]
it's probably because you open the same database with two different containers and you did not share the filestore

just use a [db-filter](https://www.odoo.com/documentation/9.0/setup/deploy.html#dbfilter) and it'll work

**Comment by hnaparst** [comment]
It would be very useful to give an example of how to do this in the documentation for the image.  The alternative is that people who want to do this have to go through a long Google search that turns up nothing and then file a bug report. This seems counterproductive.
