### ISSUE TITLE
docker odoo10.0 less css 404

### ISSUE THREAD

**Issue by 423230557** [odoo/docker#90]
when i installed a theme(like:Material/United Backend Theme)  then all the css file get error (404)
url likes:
http://127.0.0.1:8069/web/static/lib/bootstrap/less/web.assets_backend/variables.less.css

odoo@89df78ec68ac:/usr/lib/python2.7/dist-packages/odoo/addons/web/static/lib/bootstrap/less   
i search this directory, didn't find web.assets_backend/variables.less.css

is permissions make this ?

**Comment by sle-odoo** [comment]
Hello,
This theme seems to only support Odoo9 and you're installing it over Odoo10. Besides, this theme is developed by the community, not by Odoo, so you should contact them.

Regards
