### ISSUE TITLE
Issue with sending emails

### ISSUE THREAD

**Issue by kdinesh1** [odoo/docker#94]
Get the following issue while trying to send invitation mail to new users:

```
Mail delivery failed via SMTP server 'localhost'.
error: 111
Connection refused
```

![2017-01-02 17_13_22-kum - odoo](https://cloud.githubusercontent.com/assets/24737526/21586724/00120854-d10f-11e6-8a86-8a939e3c096f.png)

**Comment by sle-odoo** [comment]
Hello,
Odoo cannot send emails on its own, you need to setup a mail server to work with Odoo. This is done in the general settings i believe.

Regards
