### ISSUE TITLE
Addons

### ISSUE THREAD

**Issue by lucasrabelo** [odoo/docker#95]
Hi, just starting using this image. How do I add my custom addons?

**Comment by sle-odoo** [comment]
Hello,
Please have a look at our documentation at https://hub.docker.com/_/odoo/, especially "mount custom addons" or "Docker Compose examples" according to the way you launch the container.

Regards

**Comment by SalahAdDin** [comment]
i did that and i 'm not getting the addons.

**Comment by icewing02** [comment]
Same here.
