### ISSUE TITLE
watchdog dependency

### ISSUE THREAD

**Issue by lem8r** [odoo/docker#98]
If Odoo is started with --dev=all option there is error importing watchdog module

``` WARNING ? odoo.service.server: 'watchdog' module not installed. Code autoreload feature is disabled```

**Comment by pasgou** [comment]
pythonify is replaced by this one.

**Comment by lastalfriday** [comment]
@pasgou what do you mean? I use the Odoo 11 docker image and the warning is still there. I installed watchdog manually in the container, and all works perfectly. Why the docker image don't ship with watchdog is beyond me though

**Comment by pasgou** [comment]
Follow the link send by sle-odoo to correct your image on your own server.
I don't mean anything, I search why it doesn't work and give the answer if I find it.

You have to correct the dockerfile if you use a wrong file or if the official depot is buggy.

**Comment by fractalf** [comment]
OK, I understood what you meant afterwards. Basically *pythonify* was replaced by *watchdog*. This was fixed in versions <= 10, but not 11. I made an issue which is now resolved here https://github.com/odoo/docker/issues/194

**Comment by jbarreraballestas** [comment]
I know it's an old problem, but if anyone needs it.
I fix this  `WARNING ? odoo.service.server: 'watchdog' module not installed. Code autoreload feature is disabled` installing watchdog.

```bash
pip install watchdog
```
