### ISSUE TITLE
Synology docker problem

### ISSUE THREAD

**Issue by matraz17** [odoo/docker#99]
Hi,
I'm using docker from a NAS/Synology. It's working fine except for your ODOO products ... the server NAS/Docker return a "failed to query registry".
What's wrong ... probably not the synology, the Docker repository seems to be ok ...
Could you help ?
Alternatively, I can add an image from an URL or a File. Could you provide these links for ODOO 10 ?
Or the file? U don't understand how to do the workaround...?
Thank you,

**Comment by pasgou** [comment]
It s a problem with docker DNS. i don't know about docker in Synology, but on the docker website, they write about this trouble. They say to configure internal DNS to talk with an external DNS like google's ones (8.8.8.8).
